### ISSUE TITLE
Create scripts for Polling Kookoo logs

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#107]
**Is your feature request related to a problem? Please describe.**
This issue is an action item from https://github.com/DostEducation/RP_IVR_analytics/issues/95#issuecomment-843763395. Once we finalize the architecture and tech stack design targetted in #106, we need to parse the KooKoo API logs and store them into our database.

**Describe the solution you'd like**
- [ ] Write and implement the script that will fetch KooKoo logs from API.
- [ ] Decide the DB structure.
- [ ] Store relevant data to database.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by GauravGusain98** [comment]
This is completed. Closing
