### ISSUE TITLE
Iterations for Data source for health and funnel metric

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#114]
**Is your feature request related to a problem? Please describe.**
As moving forward, we need to make changes in charts and data sources.

**Describe the solution you'd like**
- [ ] Create new data sources if required.
- [ ] Update existing data sources as required.
- [ ] Create new stories if required

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Satendra-SR** [comment]
This remained unused, we can take it forward to the next sprint.

**Comment by rudresh** [comment]
- Renamed the column `user_phone` to `user_phone_number` in `user_experience` data source. This change now allows data studio to apply the filter on all charts as the column name is now consistent across all data sources.

**Comment by rudresh** [comment]
There are few data discrepancies in the funnel metrics. The details are captured [here](https://docs.google.com/spreadsheets/d/13aBOpTelHUkod_xEoLY8G7OieLPi-aDU1pdnb6hq01A/edit?ts=60e2cf28#gid=1442269489)

**Comment by rudresh** [comment]
@prtkdost  capturing the debugging session feedback: 
1. Update the data sources to include both content and non-content calls
2. `is_content` should be true for the content calls
3. For non-content call the value of the following should be null
    1. `corrected_listen_seconds`, 
    2. `total_content_duration`, 
    3. `average_listen_rate`, 
    4. `engagement_level`, 
    5. `is_user_active`
4. There are few remaining discrepancies with `is_call_delivered`

**Comment by prtkdost** [comment]
Cool. Also change the formula for is_user_active from > to >=20.

**Comment by rudresh** [comment]
- [ ] `toatal_unique_content_delivered` should only calculate where flow_category is `content` otherwise show null.
- [ ] `average_listen_rate` should come null but coming as 0. Possibly, the check for flow_category `content` is missing
- [ ] `engagement_level` should show `null` where flow_category is not `content`

**Comment by rudresh** [comment]
Add the following fields in all the 8 engagement data source
- [ ] `program_name`
- [ ] `preferred_time_slot`
- [ ] `signup_status`
- [ ] `partner_name`
- [ ] `district`
- [ ] `parent_type`

**Comment by rudresh** [comment]
- [ ] add a new column `is_current_week`, `is_current_month` in the useragewise data sources.

**Comment by rudresh** [comment]
Update the engagement data sources to include 
 - [ ] `total_prompt_delivered` - count the total number of content having prompts. Include if the content was delivered multiple times.
 - [ ] `total_prompt_responded` - count if a single prompt was answered that day. If there are more than one prompt responded in a day, count it as one.

**Comment by Satendra-SR** [comment]
Check if there are nullable content ids in the prompt and prompt response table. If they are after 1 June, we need to fix that.

**Comment by Satendra-SR** [comment]
Closing this as validated with @prtkdost
