### ISSUE TITLE
Fetch call logs from KooKoo

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#12]
We need a way to get call logs from KooKoo.

- [x]  Research/explore how we can get call logs from the KooKoo platform.
- [x] Implementation / Code changes required (Please create a separate issue based on our findings)

**Comment by rudresh** [comment]
My findings are as below:
1. We need to set the callback URL to Dost callback system to capture the call details.
2. The user `unicef_sub` doesn't have access to set or change that.
3. I'm not sure if UNICEF would allow setting up callback URL for Dost. Need to check with the UNICEF team

**Comment by rudresh** [comment]
I setup a Pilot Dost callback system that captures all the call related events in kookoo.

**Comment by Satendra-SR** [comment]
This is deployed on prod as a separate Google cloud funciton.
