### ISSUE TITLE
Setup Staging environment for dostadmin

### ISSUE THREAD

**Issue by rudresh** [DostEducation/RP_IVR_analytics#122]
**Is your feature request related to a problem? Please describe.**
Currently, we don't have an environment where we test new features or bug fixes before we make it live on production. There is a significant risk of the production environment getting left unstable. 

**Describe the solution you'd like**
Setup a staging environment that is a replica of the production environment. 
- [ ] Setup staging application on a new compute engine.
- [ ] Create a new database for the staging environment with the copy of the prod database. Scrub the data for staging use.
- [ ] Research and make required changes in the Exotel end for the staging environment. Will connect to  @prtkdost 
- [ ] Update the cron accordingly.

**Scrub data from following tables:**
1. Content 
2. Program
3. program seq
4. Ivr prompt response 
5. Partners 
6. Channel
7. user
8. campaign
9. experience
10. experience pause log
11. engagement
12. change request

Add more to the list if exists

**Comment by Satendra-SR** [comment]
Closing this in favor of https://github.com/DostEducation/admindashboard/issues/380
