### ISSUE TITLE
User Module content table is not populating properly

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#127]
**Describe the bug**
The `user_module_content` table is used to capture the module and content delivered to a user. But some it is not populated correctly.

**Expected behavior**
The table `user_module_content` should populate correctly.

**Additional context**
N/A

**Comment by Satendra-SR** [comment]
@prtkdost 
If the same content is going multiple times to a user then in that case only one entry is done in `user_module_content` table. Do we need to make an entry every time a call log is created despite of checking if the same content has already gone for the user. 

Let me know your thought. Here is an example of such case: 

![image](https://user-images.githubusercontent.com/39792899/126173397-63686284-3814-4f6b-97c5-59acd817124f.png)

![image](https://user-images.githubusercontent.com/39792899/126173661-126cc8ff-141b-4992-b9c8-5b89634b1a82.png)

**Comment by prtkdost** [comment]
No. one time is enough.

**Comment by Satendra-SR** [comment]
### Observations
- The contents are delivering correctly as per the `user_module_content` table. 
- The user_module_content_id is not being populated in the `call_log` table

**Comment by Satendra-SR** [comment]
Check the impact and decide on backfilling based on it.

**Comment by Satendra-SR** [comment]
@prtkdost This has been fixed and the backfilling is also done. Closing this now.
