### ISSUE TITLE
User’s registration date is incorrectly filled (Migration)

### ISSUE THREAD

**Issue by rudresh** [DostEducation/RP_IVR_analytics#133]
Registration date for some users is not populated correctly while migration. 

- [x] Verify the entries @prtkdost shared.
- [x] Find out why it happend.
- [x] Fix the data where entries are mismatching
- [x] Verify other records are correct for registration data.

**Comment by rudresh** [comment]
@prtkdost I've updated the registration date for the incorrect entries.

**Comment by Satendra-SR** [comment]
Marking this as complete and close
