### ISSUE TITLE
Don't have missed call entry but have registration entry.

### ISSUE THREAD

**Issue by rudresh** [DostEducation/RP_IVR_analytics#134]
Some of the records don't have missed call entry but have registration entry. e.g. 7081569793, 7390966403

**Comment by rudresh** [comment]
@prtkdost I checked the list that Sonia shared. All the phone numbers were given program selection option using `FINAL-DOST-Pilot-OnboardingCall1.2` flow on 18th June. 

Webhook creates a new registration if there is no entry for the phone number while making the program selection. That is why we see the registration entry even when they didn't give us the missed call.

**Comment by prtkdost** [comment]
So we create an entry in the registration in following 2 cases
- Someone is not present in our database and gives missed call for sometime
- When a webhook is called for registration flow even if there was no missed call.

am I right?

**Comment by rudresh** [comment]
Yes, that is correct.

**Comment by Satendra-SR** [comment]
Closing this as it is completed
