### ISSUE TITLE
Feedback on Funnel Metrics Data Sources

### ISSUE THREAD

**Issue by rudresh** [DostEducation/RP_IVR_analytics#136]
Feedback on funnel metrics data sources:
- [x] `daily_engagement_datewise` data source has few records for which there is at least one call delivered but `call_delivered` column is showing as null. e.g. 
    - 9984881751 on Jun 8.
    - call_delivered is coming as null
- [x] make the following column null if the call was not delivered. 
    - [x] response rate,
    - [x] listen rate,  and 
    - [x] engagement level
- [x] Engagement is coming as `Medium` even when the response rate and listen rate is 100%
    - e.g. 9984881751 on May 24 and Jun 3
- [x] Add column for the beginning of the period in all the funnel datewise data sources.
- [x] `all_call_records` is showing null user id from Prateek’s phone number

**Comment by rudresh** [comment]
@prtkdost All the issues mentioned are fixed. Please test.

`all_call_records` - shows the `registration_id` and the `user_id` at that point of time when the call was delivered. In few records you see `null` values in the `user_id` because the user was not created at that point of time.

**Comment by prtkdost** [comment]
Issues missing
- Removing blast calls from weekly, monthly, quarterly data sources.

**Comment by rudresh** [comment]
@prtkdost I've updated the weekly, monthly and quarterly data sources to include the records where flow_category is `null` or `content`. So, `blast`, `registration` and `survey` calls won't be accounted for in the calculation.

Please test it.

**Comment by Satendra-SR** [comment]
Closing this item.
