### ISSUE TITLE
Research on the database connections for cloud function

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#14]
In initial phase, we got in trouble with how we are connecting our staging database with Google cloud SQL service.

Initial Findings:
There are some issues with TCP based connections while connecting a Google cloud functions with GCP SQL service. The other option we researched is, we can use a socket based connection.

- [x] The way we can connect our application to database using a socket based connection.
- [x] Research for using ORM or SQL based approach.
- [x] Code changes based on the research item above.

**Comment by rudresh** [comment]
@Satendra-SR We can use the below method to make the socket based database connection.

`SQLALCHEMY_DATABASE_URI = 'postgresql://username:password@/database_name?host=pathofsocket'`
In our case `pathofsocket` will be something like `/cloudsql/connection_name`. The connection name can be picked from the cloud sql interface

**Comment by Satendra-SR** [comment]
@rudresh yeah! great. Thanks for sharing. Making the changes based on the research.

**Comment by Satendra-SR** [comment]
The socket based DB connection is working properly on both staging and prod setup. Closing this item.
