### ISSUE TITLE
Discrepencies in user signup status

### ISSUE THREAD

**Issue by prtkdost** [DostEducation/RP_IVR_analytics#143]
**Describe the bug**
I verified data of registrations and signups for 5Jul-11Jul. I found following errors
1. users who signedup but marked incomplete - 1 user - 9554199034
2. users who didnt signedup but marked complete - 166 users - [here](https://drive.google.com/file/d/18CZ21612Fb4WqFSNxeKcFBhrN4TRJPos/view?usp=sharing)
3. Users who signed up but dont have entry in ivr_prompt_response table - 4 users - [here](https://docs.google.com/spreadsheets/d/18CZ21612Fb4WqFSNxeKcFBhrN4TRJPos/edit#gid=373238240)

**To Reproduce**
1. Compare entries in RP flow report, registration table, ivr prompt response table.

**Expected behavior**
1. All prompt responses should have entry in ivr prompt response table.
2. All users who have signup prompt entries in ivr prompt response table should be marked complete
3. No user who have signup prompt entry in IVR prompt response should be marked incomplete

**Comment by Satendra-SR** [comment]
> * users who signedup but marked incomplete - 1 user - 9554199034
> * users who didnt signedup but marked complete - 166 users - [here](https://drive.google.com/file/d/18CZ21612Fb4WqFSNxeKcFBhrN4TRJPos/view?usp=sharing)
> * Users who signed up but dont have entry in ivr_prompt_response table - 4 users - [here](https://docs.google.com/spreadsheets/d/18CZ21612Fb4WqFSNxeKcFBhrN4TRJPos/edit#gid=373238240)

@prtkdost 
1. We will keep an eye on this as there is only one such entry. 
2. For this I have made the fixes in the codebase. It'll be resolved now.
3. It seems this was happening due to issue #131 and is already fixed.

**Comment by Satendra-SR** [comment]
- [ ] Check the signup status is correctly marked in the registration table. List down if found in consistent behavior.

**Comment by Satendra-SR** [comment]
[Here is the list](https://docs.google.com/spreadsheets/d/1QBQNuALOBjdPmw6xxyku7C6qQNyMHjE_PsG0A6LcXZs/edit#gid=540245997) of users having incorrect signup status.

**Comment by Satendra-SR** [comment]
Backfilled the data successfully.

**Comment by Satendra-SR** [comment]
This is fixed. Closing this issue.
