### ISSUE TITLE
unicef-user-custom-fields table not getting populated properly.

### ISSUE THREAD

**Issue by prtkdost** [DostEducation/RP_IVR_analytics#146]
**Describe the bug**
It shows only 5 unique field names whereas there are many custom fields. Like
DOST-CONTENT-COMPLETED
DOST-CC

**To Reproduce**

**Expected behavior**
All fields with prefix Dost should be populated properly here

**Screenshots**
![image](https://user-images.githubusercontent.com/69189579/125936175-ad43b138-8736-47ca-8243-5c4c00e18322.png)

**Comment by Satendra-SR** [comment]
Diagnosis on this

**Comment by Satendra-SR** [comment]
Tested it on staging and the table is being populated correctly.

**Comment by Satendra-SR** [comment]
Also, the records are being captured in the production as well. Here is the image showing such entries:
<img width="1102" alt="Screenshot 2021-08-09 at 2 30 33 PM" src="https://user-images.githubusercontent.com/39792899/128682684-47b2c3e3-87b7-416d-b979-90e9f43e4451.png">

**Comment by Satendra-SR** [comment]
For `DOST-CONTENT-COMPLETED` field the slug name and the tag name are different. 
For this field, the entry in the database will be with the `dost_flow_status`
![image](https://user-images.githubusercontent.com/39792899/128687064-3eaf8a5c-8537-4bb7-ad62-59afa75eae95.png)

**Comment by Satendra-SR** [comment]
| Custom fields available in RP  | Custom fields available in database | Comment |
| ------------- | ------------- | ------------- |
| dost_cc  | No  | This field is not used in any flow  |
| dost_flow_status  | Yes  | Available in database. The label for this field in RP is named as `DOST-CONTENT-COMPLETED` but in the database only slug name is captured not label name  |
| dost_module10_streak  | Yes  | Available in database  |
| dost_module5_streak  | Yes  | Available in database  |
| dost_module7_streak  | No  | This field is not used in any flow  |
| dost_program  | Yes  | Available in database  |
| dost_time  | Yes  | Available in database  |
| dost_ttr_group  | No  | This field is only used in [1 flow](https://rapidpro.ilhasoft.in/flow/editor/61009617-d7b5-4c96-b7fd-24a69dd611e6/) and there are no call record for that flow |

**Comment by prtkdost** [comment]
The field will only be updated if it is present in a flow? I was under the impression that even if its not in the flow, if I am calling webhook I will get all user custom fields and if there are any changes it will be updated.

**Comment by Satendra-SR** [comment]
@prtkdost 
The fields are the property of the user and we will receive all the fields in every Webhooks. 

If the value of any field is null then we will receive the null value in all Webhooks unless its value is updated. We do not capture the fields having null value

![image](https://user-images.githubusercontent.com/39792899/128966387-53a72e25-bddd-4fe4-9fdb-405aaaa618e8.png)

**Comment by prtkdost** [comment]
Cool thank you. Looks good. I will verify it with rapidpro data lil bit and then we can close it.

**Comment by prtkdost** [comment]
Field:Dost-time

![image](https://user-images.githubusercontent.com/69189579/129529729-0d5459df-7e21-466d-af11-f493bb2ed7a3.png)
![image](https://user-images.githubusercontent.com/69189579/129529764-00301d4e-474a-4aa1-89dd-f70a65c81a7f.png)

Field:Dost-Signup-Status

![image](https://user-images.githubusercontent.com/69189579/129529912-b2435998-f065-4c3c-8394-36278f99f4ec.png)
![image](https://user-images.githubusercontent.com/69189579/129529966-e6c3e910-b479-48d1-a186-058aa0d98eef.png)

Field:Dost-Program
![image](https://user-images.githubusercontent.com/69189579/129530054-91f0bc03-c3c9-4b3f-8f6c-7f8b5dc8361f.png)
![image](https://user-images.githubusercontent.com/69189579/129530111-2998e69c-3fe7-4630-9d67-5cfb8c029625.png)

You can download contact report for Dost-Pilot-Intro group to verify and debug. I would go deeper and give to individual samples to check, but since differences are so large, I am not sure if that is the best approach. Let me know if you want me to do that.

**Comment by Satendra-SR** [comment]
@prtkdost 

Here are the details of the observation that I have:
- Currently, the system stores multiple entries for the same custom_fields if the values are different. Let me know If we want a similar type of behaviour as we have in groups, where we mark them as active and inactive.
- For many users, the fields are updated today in RapidPro. So for them, the data regarding the custom_field will be updated in tomorrow's call. As in today's webhook, the data regarding the custom_field is not available, it will be available in the next day's call.

Due to these reasons, we can see the inconsistency in the Rapid pro report and our database.

**Comment by Satendra-SR** [comment]
We have created two different items based on the research we did on this particular issue.
1. #168 
2. #167

**Comment by Satendra-SR** [comment]
Closing this item now.
