### ISSUE TITLE
Diagnose the inconsistent behaviour with Data Studio

### ISSUE THREAD

**Issue by rudresh** [DostEducation/RP_IVR_analytics#149]
Diagnose the inconsistent behaviour with the chart loading in the Data Studio

**Comment by rudresh** [comment]
Few of the things I have tried are:
- [ ] Create read-replica of the database
- [ ] Point all the data sources to use the read-replica
- [ ] Format the phone numbers in all the table to keep the last 10 characters of the phone number
- [ ] Add indexing on the formatted phone numbers
- [ ] Use the formatted phone numbers in the queries.

**Comment by rudresh** [comment]
-[ ] Update the flags `max_standby_archive_delay` and `max_standby_streaming_delay` to a suitable value on the replica db

**Comment by Satendra-SR** [comment]
Add the more items we are trying out to fix this.

**Comment by Satendra-SR** [comment]
@prtkdost There are some changes in the way we are using the data sources now. We have created the materialized view now which is comparatively faster than we had initially.

Could you please test?

**Comment by Satendra-SR** [comment]
Check With @rudresh

**Comment by Satendra-SR** [comment]
Closing this now.
