### ISSUE TITLE
All entries not getting captured in ivrresponse table

### ISSUE THREAD

**Issue by gandhisonia** [DostEducation/RP_IVR_analytics#153]
**Describe the bug**
The number of users responding to a question are not the same between the RapidPro flow and the `ivrresponse` table on Data Studio.

**To Reproduce**
1. Check the number of flow runs of the TTR survey ([1](https://rapidpro.ilhasoft.in/flow/editor/39ef3343-d487-4b56-929e-5cf928f5406e/) and [2](https://rapidpro.ilhasoft.in/flow/editor/a73e384f-d122-472d-882a-f6642a180161/))
2. Check the unique phone numbers or flow runs on Data Studio for content ID `118` for these two flows
3. Another way is to access [this](https://datastudio.google.com/reporting/ec1e09bf-cc2d-4832-af5f-86b1eced28a6/page/OKQVC) Data Studio report's page 2's third table (T-6)
4. Instead of looking at flow runs, we can also look at the number of times the webhook plaed after the first menu selection was called in each flow (this will tell us the number of people who got past the first prompt question)

**Expected behavior**
All IVR data flowing through RP needs to be captured in the database.

**Screenshots**
Webhook (99) + Webhook (147) is not equal to Data Studio (136)
![image](https://user-images.githubusercontent.com/74590561/126600546-28292db3-5c3b-47dc-a2a2-fb0daf440bf1.png)
![image](https://user-images.githubusercontent.com/74590561/126600606-800014be-656a-42c7-85d5-978eac600769.png)
![image](https://user-images.githubusercontent.com/74590561/126600622-6dba12b4-b093-41d2-840c-76e29c8f0546.png)

**Environment (please complete the following information):**
 - Webhook Payload ``` here```

**Additional context**

**Comment by gandhisonia** [comment]
This webhook may also contain cases where the User has requested for a repeat of Q (listening to it again).

**Comment by Satendra-SR** [comment]
All the webhook related to the options in the prompt are being captured correctly. The webhooks for the `repeat` and `other` responses are less in number than the count in the rapidpro flow.

**Comment by gandhisonia** [comment]
Hi Satendra, I got your point. I still have a feeling there is a leak somewhere. Can we cross verify using the results report from each flow? All numbers in the report from RP would be people who picked up the calls. As a result, that number should match the count of numbers captured in the database.

**Comment by Satendra-SR** [comment]
Ok @sonia, I'll the count of the user who picked the call from the report and compare that with the unique users count fro which we have captured the responses.

**Comment by Satendra-SR** [comment]
@gandhisonia , I checked the report and compare that with the database records. I found that all the entries except for `repeat` and `others` are captured correctly. I also tried to replicate this in staging and found that for the first webhook call only the `other` and `repeat` response are not coming. 

This is happening because when the user select `repeat` or `other` option then the webhook is not triggered for that response and if the user selects any other option afterward then the webhook is triggered for that response and we miss the response of the `other` and `repeat` options. 

To resolve this we need to add a webhook section just before the menu selection instead of adding it before the retry loop, like we have done in the (2,3,4 and 5) menu selection. 
 
![image](https://user-images.githubusercontent.com/39792899/127651905-f482d49d-b6a6-4dea-8454-0aa8de0e55e1.png)

**Comment by gandhisonia** [comment]
Got it, Satendra. Noted on the placement of the first webhook.
Thanks for checking. Allow me to go through this once from my end too. I will post here once I am done.

**Comment by Satendra-SR** [comment]
@gandhisonia Please let me know if you need any help in updating the webhook. Moving it to the accepted bucket.

**Comment by Satendra-SR** [comment]
Check on slack

**Comment by gandhisonia** [comment]
Hi @Satendra-SR , thank you for being patient -- I checked this from my end.

Steps I used for testing:
1. Picked these two flows: [Flow 1](https://rapidpro.ilhasoft.in/flow/editor/39ef3343-d487-4b56-929e-5cf928f5406e/) and [Flow 2](https://rapidpro.ilhasoft.in/flow/editor/a73e384f-d122-472d-882a-f6642a180161/). Downloaded reports for both from RP.
2. Filtered entries for July 26 -- all URNs are unique
3. Created a chart on Data Studio for this day and content ID 118. Only these two flows were sent on 26-Jul. Please refer last chart on Page 3 of [this dashboard](https://datastudio.google.com/reporting/ec1e09bf-cc2d-4832-af5f-86b1eced28a6/page/p_b2es6ghfmc). Downloaded data from this.
4. Brought both the data are on [this file](https://docs.google.com/spreadsheets/d/1o1WafPxbO77xd_rN8LfxSkTB0vso3Fw2T9E_qLLRlP8/edit?urlBuilderDomain=dosteducation.com#gid=0) on separate sheets.
5. Yellow column with `No` on second sheet are the ones that are missed out on Data Studio. If you filter them you'll see these are calls picked up by Users but the first response is any invalid selection. They can be seen on the RP report but not the database.

6. This I think is in sync with what you mentioned in your comment from Jul 30. 

@prtkdost just FYI : we need to change the flows according to what Satendra has suggested reagrding placement of the first webhook in order to capture all responses. These responses are essential for us to understand how well the Users are able to grasp the questions.

**Comment by gandhisonia** [comment]
Feel free to close this, @Satendra-SR . The next time we run a similar flow, I'll do a check again to see if all are getting captured then.

**Comment by gandhisonia** [comment]
Total entries in RapidPro: 585
Entries not getting captured in database: 180 / 585 **[28.21%]**

Users who got both flows: 122 / 585 **[20.85%]**

**Comment by Satendra-SR** [comment]
Closing this issue
