### ISSUE TITLE
Mark user unsubscribed based on prompt selection or custom contact field

### ISSUE THREAD

**Issue by prtkdost** [DostEducation/RP_IVR_analytics#156]
**Is your feature request related to a problem? Please describe.**
If a user do not signup after multiple attempts, or remain low engaged for extended time, we want to offer them an unsubscribe option to stop the program if they want. They can give us prompt response and based on that we can stop their calls and mark them unsubscribes.

**Describe the solution you'd like**
The stopping of calls can be managed at rapidpro level by putting them in a different contact field.

For changing the user status in registration, user, and user program table, we can use the prompt mapping for this. If an unsub prompt is recorded for user, we mark them unsub.

**Describe alternatives you've considered**
We can also the custom contact field "Dost-Signup-Status". If it is marked as unsub, we can mark the user as unsub in our database.

**Additional context**
You can check the unsub node in this flow - https://rapidpro.ilhasoft.in/flow/editor/c90153bd-961d-48b3-b847-1ae3070a24e7/

**Comment by Satendra-SR** [comment]
@prtkdost is there any plan to mark user program back to the active state if they give a missed call again?

**Comment by Satendra-SR** [comment]
Check if this is possible with prompt

**Comment by Sachinbisht27** [comment]
Closing as completed
