### ISSUE TITLE
[Research] The possibility of creating alerts in datastudio

### ISSUE THREAD

**Issue by rudresh** [DostEducation/RP_IVR_analytics#157]
Usual use cases:
1. Webhook failure
2. Users not getting calls.
3. Some time slot not getting called
4. Callbacks are not going out timely
5. If a flow didn't run for more than 3-4 days
6. Call lag >5%
7. IVR Prompt Response not getting populated properly.

### Todo:
- [ ] Find a way to alert via email/slack.
- [ ] Create stories based on the finding and above requirements.

**Comment by Satendra-SR** [comment]
Opened new issue #172 for implementing this task using a different approach. Hence closing this now.
