### ISSUE TITLE
Enhancements in user_custom_fields table

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#167]
**Is your request related to a problem? Please describe.**
There is a need for maintaining status in the user custom fields table

**Describe the solution you'd like**
- [x] Add new column `status` in user_custom_fields table.
- [x] Update codebase to handle user custom status.
- [x] See if any backfill is required

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by GauravGusain98** [comment]
This is deployed and the data has been verified. Closing this now.
