### ISSUE TITLE
Cron based refresh materialized views

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#173]
**Is your feature request related to a problem? Please describe.**
Currently, we need to refresh materialized view manually. This needs to be done automatically.

**Describe the solution you'd like**
We need to create a cronjob to refresh materialized view daily. 

**Describe alternatives you've considered**
NA

**Additional context**
NA

- Check if we need multiple cronjobs or a single cronjob will work.
- Need to create a new database connection for the analytics database.
- Need to allow database access to this server.

**Comment by Satendra-SR** [comment]
@GauravGusain98 let's test this tonight

**Comment by GauravGusain98** [comment]
This is working fine and the views are getting refreshed every night. Hence closing this
