### ISSUE TITLE
[Production] GCP functions error: The request was aborted because there was no available instance

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#176]
**Is your request related to a problem? Please describe.**
We are using GCP functions to handle the webhook request. It is working fine, but there are a few incidents where we are getting the error `The request was aborted because there was no available instance`.

**Describe the solution you'd like**
- [ ] Check the root cause and come up with the required solution.
- [ ] As the request load started increasing, need to come up with a future plan for how we are going to handle if this will increase in the future.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Sachinbisht27** [comment]
I am closing as it is not needed now.
