### ISSUE TITLE
Handle `Other` IVR prompt response correctly (possible solution only)

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#185]
**Is your feature request related to a problem? Please describe.**
For some IVR prompts, we have preseeded responses as `**_OTHER` but for some prompts, we don't or have other naming conventions which makes it difficult to capture the responses correctly.

**Describe the solution you'd like**
- [ ] Come up with a common naming convention.
- [ ] Code changes that are required to make such changes (create a new ticket)

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by GauravGusain98** [comment]
### Problem
1. For some IVR prompts, we have keypress responses with the name `Other`, and Flow builder also provides us a default response with the name `Other`. This makes it difficult to distinguish if the response that we got is the default one that comes when the user presses something incorrect or if it is the `Other` option response.
2. The district values in the Registration table also contain values like `Anyother` (for other districts) and `Other` (When the user pressed something incorrect). We don't need the `Other` value to be populated in the Registration table. 

### Solution
1. After checking the IVR prompt response table, the entries there are looking fine. Also, in the IVR prompts table there was no entry for the response having a keypress and with the name `Other`. 
All the IVR prompts that are having `Other` as a response are not mapped with any Keypress which is correct as for any incorrect keypress we need the response as `Other`. So there is nothing to be done in the IVR prompts mapping part.
2. We need to update the logic to not update the district for the users who have pressed a incorrect key.

**Comment by GauravGusain98** [comment]
### Possible Solution

- [ ] Based on Keypress, mark the response as `WRONG_PRESS` or `NO_PRESS`.
- [ ] Backfill the data

There will be no `OTHER` value in the response. we will use `ANYOTHER` as an option.

**Comment by GauravGusain98** [comment]
A new issue #207 has been created for the solution proposed in this story. Therefore, closing this now.
