### ISSUE TITLE
[Convention] Explore the status for un-signed-up user who completes the program

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#187]
**Is your feature request related to a problem? Please describe.**
There are possibilities that the user didn't sign up but complete the program. For now, the registration status remains `pending` or `inprogress`.
Also, we maintain the status at 2 places
- `user_program` table (to capture whether the user have completed the program or is in progress)
- `registration` table (to capture whether the user have signed up or not)

A similar case is coming to the admin dashboard project where we have a single place to capture the status currently (`experience` table). If the user has pending signup, we mark the experience as `pending`, where are if the user completes that particular program, we mark it as complete, which doesn't seem correct.

**Describe the solution you'd like**
- [ ] Discuss and come up to a convention.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by GauravGusain98** [comment]
Sharing the [document](https://www.notion.so/dosteducation/03fcfa4fb18b4f15bdfa0859834b3663?v=c86f84c53e8446bbadc13373ad649ab1&p=9e941642b60a41bc812b107a476909cc) for different cases that may occur from user creation to user completing a program and different status that are being used or can be used in these cases. 

### Action Items
- [ ] Build logic to find if the last content has been delivered to the user
- [ ] Update the status of user_program to `complete`

**Comment by GauravGusain98** [comment]
A new issue #208 is created for the implementation of the solution proposed in this story. Hence closing this now.
