### ISSUE TITLE
Mark user as "Unsubscribe" in our database

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#189]
**Is your feature request related to a problem? Please describe.**
Currently, we are not capturing any status for unsubscribing users (though we are getting IVR prompt responses for this).

**Describe the solution you'd like**
- [ ] Mark these user's `user_program` as unsubscribe
- [ ] Backfill the earlier user who has opted to unsubscribe.

**Describe alternatives you've considered**
None

**Additional context**
None

**Need confirmation**
What will be the signup status after user select no/other to the unsubscribe prompt but didn't selected any program yet

**Comment by vivek-kumar-pandey** [comment]
We completed this issue with https://github.com/DostEducation/RP_IVR_analytics/issues/257, so closing this issue
