### ISSUE TITLE
Unable to find users in weekly datewise data source

### ISSUE THREAD

**Issue by rudresh** [DostEducation/RP_IVR_analytics#191]
There are few users that are not showing up in the weekly datewise data source. Sample are available [here](https://docs.google.com/spreadsheets/d/1XmQuxHliMUU33kjm8D3vmD-vi4Slh1neZ8J8H9zN0ms/edit#gid=0)

### Dev Notes
Verify if we are not hitting data limit in Google Data Studio

**Comment by rudresh** [comment]
@prtkdost users are available in the data source. It is visible when you create a chart/report. 

While using the `Explore` option in the data source, there is limit to the numbers of phone numbers that can appear in the filter. There is a generic filter for the remaining items at the bottom. You can use that.

**Comment by Satendra-SR** [comment]
Closing this as the issue was with the limit. The data sources have valid data.
