### ISSUE TITLE
While blending engagement Datasource with custom fields data source, the record count decreases.

### ISSUE THREAD

**Issue by rudresh** [DostEducation/RP_IVR_analytics#198]
While blending engagement Datasource with custom fields data source, the record count decreases.

### Dev Notes
Check blending for all call records and registration.

**Comment by rudresh** [comment]
Data studio is not able to process records beyond a certain volume of data. When we blend data a cartesian product is created. On occasions when the number of records are beyond what data studio can handle we get unpredictable behaviours, like reduced total count of records. 

A work around is to add filters on individual data sources before blending them. This reduces the volume of blended records.

**Comment by Satendra-SR** [comment]
- [ ] Need to share the guideline with @prtkdost and @gandhisonia

**Comment by rudresh** [comment]
@prtkdost @gandhisonia I've captured the guidelines [here](https://www.notion.so/dosteducation/Data-Studio-b359d1b254ed4817b8771e19d036ac9b).

**Comment by GauravGusain98** [comment]
This is completed. Closing this.
