### ISSUE TITLE
Design tech stack for the application

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#2]
It includes
- [x] How will we get data from RP/Kookoo to our database. Will it be a cloud function to a server.
- [x] Which database we will use?
- [x] Where does the DB reside?
- [x] Do we need to use any managed services?
- [x] Which BI tool we are going with? `chartio` / `Data Studio` or anything else. Check the performance and cost implications.
- [x] How will we connect the DB to the BI tool?

**Comment by rudresh** [comment]
Sharing the WIP document [here](https://docs.google.com/presentation/d/17OkRx3N8c98La2Dl2OS-bRxAhV-aoSmqWd0ADvcVdI8/edit#slide=id.gbad61d0af8_0_12)

**Comment by rudresh** [comment]
Sharing the link of finalized version [here](https://drive.google.com/file/d/1iK0CGveK8d0kM6Omeh7GyfU8iK0Hc2jT/view?usp=sharing)

**Comment by Satendra-SR** [comment]
Closing this as it is marked as accepted and complete in the sheet.
