### ISSUE TITLE
For some users the preferred time slot is not matching the custom field value

### ISSUE THREAD

**Issue by GauravGusain98** [DostEducation/RP_IVR_analytics#206]
**Describe the bug**
Many users are getting calls at different time slots. Due to this, we are getting daily alerts for calls going out in different time slots.

**To Reproduce**
NA

**Expected behavior**
The value of the preferred timeslot should match the custom field's value.

**Screenshots**
![image](https://user-images.githubusercontent.com/39792899/142596291-6ee6daa6-e695-437e-9b04-4bf719a64e63.png)

**Environment (please complete the following information):**
 - Webhook Payload ``` here```

**Additional context**
NA

**Comment by GauravGusain98** [comment]
@prtkdost Sharing the list of users having incorrect time slots
https://docs.google.com/spreadsheets/d/1__vHB7hwDesPACoAqFajwVR22q4pPRCJI03RPN8rXdo/edit#gid=0

**Comment by Satendra-SR** [comment]
Comeup with diagnosis and the impact.

**Comment by Satendra-SR** [comment]
Check the preferred time slot, if it is being updated correctly.

**Comment by GauravGusain98** [comment]
### Diagnosis Report
[Report Sheet Link](https://docs.google.com/spreadsheets/d/1__vHB7hwDesPACoAqFajwVR22q4pPRCJI03RPN8rXdo/edit#gid=1021652244)

There are a few issues that came out after the diagnosis:
1. There are 240 old users (march and before) for whom the timeslots are not updated
2. There are 48 users who accidentally got time change blast
3. There are 18 users for whom we don't have responses for the correct time slot
4. For 2 users the Rapid pro custom field value is incorrect, else all the data is correct
5. For 233 users we didn't receive a time opt-in prompt because they drop in before the time selection ivr menu
6. 71 users got affected due to the incorrect Rapid pro flow design which got corrected after 17 Aug
7. 468 users have preferred time slot as `Other` instead of `AFTERNOON`

**Comment by Satendra-SR** [comment]
- [ ] Create alerts for time slot, compare `custom_fields` with `user_program`

**Comment by GauravGusain98** [comment]
@prtkdost 
Here are the details of the 5th issue mentioned in the above Diagnosis:
- Some user has already opted for a time opt-in and for that response we have updated their time slot value accordingly.
- Some of the users again received the time opt-in prompt and this time they drop before the time selection prompt.
- In the flow, we are updating user time to 0 before the time opt-in IVR menu. So the rapid pro the time-slot custom fields for these users are updated to 0.
- As users drop before the flow reaches the webhook node then we don't receive that webhook call in our system
- Due to this for some users the value of the custom field is updated in Rapid pro but as we didn't receive any webhook so the time slot of these users is not updated to the new one.

**Comment by Satendra-SR** [comment]
- [ ] List down the user list who all are getting delayed the first call by 1 or 2 hours.
- [ ] Check the impact.
- [ ] Check if the delay was on RP or Ozontel (KooKoo)
- [ ] Script to get the data easily if asked again.

**Comment by Satendra-SR** [comment]
- [ ] Check for which case, the `preferred time` is storing null.

**Comment by GauravGusain98** [comment]
### How user program is created and preferred time slot is assigned
- The user_program entry for the user is only created when he/she selects a prompt. 
- The preferred timeslot is set to `AFTERNOON` when the user_program is created and is updated based on the prompt response

**Comment by Satendra-SR** [comment]
As we are moving away from this setup to unified alerts, this story is obsolete now. Closing
