### ISSUE TITLE
[Feature] Status for user who completes the program

### ISSUE THREAD

**Issue by GauravGusain98** [DostEducation/RP_IVR_analytics#208]
**Is your feature request related to a problem? Please describe.**
Sharing the [document](https://www.notion.so/dosteducation/03fcfa4fb18b4f15bdfa0859834b3663?v=c86f84c53e8446bbadc13373ad649ab1&p=9e941642b60a41bc812b107a476909cc) for different cases that may occur from user creation to user completing a program and different status that are being used or can be used in these cases. 

**Describe the solution you'd like**
- [x] Build logic to find if the last content has been delivered to the user
- [x] Update the status of user_program to `complete`

**Method to find last content of the user**
1. Add a field to the webhook payload of the last content of the program. We can then mark user complete based on this field. This will reduce the database query that we have to make for finding the last content of the user. Every time new content is added to the program we have to remove this new field from the old content and add it to the new content.
2. Add a custom field for completed user
3. Move the user to a particular group if he completes a program.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by GauravGusain98** [comment]
The changes are deployed in production. We just need to add `"is_last_content"` field in the post body of the webhook of the last contents.

**Comment by prtkdost** [comment]
https://rapidpro.ilhasoft.in/flow/editor/0aa1c4ac-3f66-48c3-9bb6-e1bba6811f31/
https://rapidpro.ilhasoft.in/flow/editor/e7c55b70-73c4-476c-a3d9-35b11f47f18b/

@GauravGusain98 added it. Please check

**Comment by GauravGusain98** [comment]
This is working fine. Closing this issue.
