### ISSUE TITLE
[BUG] Getting 500 Error in GCP daily

### ISSUE THREAD

**Issue by GauravGusain98** [DostEducation/RP_IVR_analytics#213]
**Describe the bug**
In both `rp-ivr-analytics-prod` and `kookoo-callback` cloud function we are getting webhook error frequently. The error that we are getting is
```
The request was aborted because there was no available instance. Additional troubleshooting documentation can be found at: https://cloud.google.com/functions/docs/troubleshooting#scalability
```

**To Reproduce**
Check the error logs of the [Cloud function](https://console.cloud.google.com/functions/details/asia-south1/rp-ivr-analytics-prod?project=cryptic-gate-211900&tab=logs)

**Expected behavior**
The webhook should be handled correctly and 

**Screenshots**
![image](https://user-images.githubusercontent.com/54376313/143993502-470bd3d7-c013-4f4f-84e4-f84b075f4160.png)

**Additional context**
Need to figure out the root cause, one of the possible reasons this might be occurring can be an increase in database queries or traffic.

**Comment by rudresh** [comment]
It appears to be an issue with GCF not able to handle the scale / spike. See the link 
https://issuetracker.google.com/issues/153207649#comment2

We are getting 500 errors, so we can try few things:
- [ ] specify the min and max instances for the functions
- [ ] review the performance of the functions
- [ ] explore if we can retry the webhook from the RapidPro flow
- [ ] implement task queue for handling the webhook calls.

**Comment by Satendra-SR** [comment]
Excluded the `user_custom_field` and `user_group` capturing flow as we are doing it at midnight as well. This has reduced the occurences.

**Comment by GauravGusain98** [comment]
To handle this type of situation in the future, we need to do some infrastructure changes. For this we have created issue [#221 Implement Queues in the GCP Infrastructure](https://github.com/DostEducation/RP_IVR_analytics/issues/221)

**Comment by Satendra-SR** [comment]
Also, this is now happening anymore. There could be some issues with GCP cloud function scaling functionality (Need to find some resource though)

**Comment by Satendra-SR** [comment]
Closing this as this is not coming now. Closing
