### ISSUE TITLE
Backfill Nov 21 and Nov 22 failed webhook calls

### ISSUE THREAD

**Issue by GauravGusain98** [DostEducation/RP_IVR_analytics#214]
**Describe the bug**
On Nov 21 and 22 we received many webhook failures due to the addition of the status column in the `user_cutom_field` table which increased the database load in the system. 

**To Reproduce**
NA

**Expected behavior**
- [ ] Find a way to fetch the failed webhook data
- [ ] We need to backfill the data of the failed webhooks

**Screenshots**
NA

**Additional context**
NA

**Comment by Satendra-SR** [comment]
This is pretty old and the backfill is also not possible/required. Closing
