### ISSUE TITLE
Add Program sequence table

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#224]
**Is your feature request related to a problem? Please describe.**
For analytics, we need to denormalize a few tables. 

**Describe the solution you'd like**
To achieve denormalization, add a new table Program sequence that can replace `program_module` and `module_content`.

**Describe alternatives you've considered**
None

**Additional context**
None

**Proposed table structure**
Table: `program_sequence`
id | program_id | module_id | content_id | sequence_index | content_status
--- | --- | --- | --- |--- |---
 1 | 1 | 1 | 1 | 2 | active  

**New column**
Add a new column to the `call_log` table `program_sequence_id`

**Backfilling**
Need to backfill all the presenting data based on the table structure

**Comment by GauravGusain98** [comment]
All the changes including the table structure and migration have been done and deployed. Closing this now.
