### ISSUE TITLE
Chartio Migration - Create data source for Self Paced Engagement (Weekly Calendar Date))

### ISSUE THREAD

**Issue by rudresh** [DostEducation/RP_IVR_analytics#229]
Create data source for Self Paced Engagement (Weekly Calendar Date)) with following fields:

- User Id
- User Age Weekly
- Phone
- User Created On
- District
- Partner
- Program
- Program Status
- User Active
- Total Unique Content Delivered
- Time for 1 Content Piece
- Total Days Call Delivered
- Total Days Call Answered
- RR
- Listen Seconds Capped
- Total Duration Secs
- Avg LS
- Avg LR
- Overall Engagement
- Total Prompts Delivered
- Total Prompts Answered
- RR Prompts

**Comment by vivek-kumar-pandey** [comment]
We are no longer using the chartio and the data sources and charts are created on the data studio. So closing this issue
