### ISSUE TITLE
Chartio Migration - Create data source for Self Paced Engagement (Monthly Calendar Date)

### ISSUE THREAD

**Issue by rudresh** [DostEducation/RP_IVR_analytics#231]
Create data source for Self Paced Engagement (Monthly Calendar Date) with following fields:

- Eng Month
- User Id
- Phone
- District
- Partner
- Program
- User Created On
- Program Status
- Maximum User Age
- Total Unique Content Delivered
- Time for 1 Content Piece
- User Active
- Total days Call Delivered
- Total days Call Answered
- RR
- Max Listen Sec Capped
- Total Duration Secs
- Avg LS
- Avg LR
- Overall Eng
- Total Prompts Delivered
- Total Prompts Answered
- RR Prompts

**Comment by vivek-kumar-pandey** [comment]
We are no longer using the chartio and the data sources and charts are created on the data studio. So closing this issue
