### ISSUE TITLE
Chartio Migration - Create data source for Self Paced Engagement (Monthly User Age Wise)

### ISSUE THREAD

**Issue by rudresh** [DostEducation/RP_IVR_analytics#232]
Create data source for Self Paced Engagement (Monthly User Age Wise) with following fields:

- User Id
- User Month
- Phone
- District
- Partner
- Program
- User Created On
- Program Status
- User Active
- Total Unique Content Delivered
- Time for 1 content piece
- Total Days Call Delivered
- Total Days Call Answered
- RR
- Maximum Listen Secs Capped
- Maximum Duration Secs
- Avg LS
- Avg LR
- Overall Eng
- Total Prompts Delivered
- Total Prompt Answered
- RR Prompts

**Comment by vivek-kumar-pandey** [comment]
We are no longer using the chartio and the data sources and charts are created on the data studio. So closing this issue
