### ISSUE TITLE
64K calls went out of window

### ISSUE THREAD

**Issue by GauravGusain98** [DostEducation/RP_IVR_analytics#234]
**Describe the bug**
on 10 Jan `63817` calls went out of the window i.e between 10 Jan 10 pm to 11 Jan 8 am. Only the calls that are triggered due to missed calls should go out within this time but 64K is a very huge number the possibility of this many calls scheduled by the missed call is very less. So we need to find why these calls went out at night.

**To Reproduce**
NA

**Expected behavior**
- [ ] Find the cause of the issue
- [x] Figure out the impact and details of all the users and calls that went out of window.
- [ ] Communicate with the Unicef team if required.

**Screenshots**
NA

**Additional context**
NA

**Comment by GauravGusain98** [comment]
### Diagnosis 
-  Total users who got outofwindow calls - 21986
- Total Missed call received - 1526
- Total Callbacks - 85046
- In window calls (outbound call only) - 20585
- Out of window calls - 63817
- User who got call in within time slots - 9639

**Report**
[Sheet Link](https://docs.google.com/spreadsheets/d/13cnQ-eUcWmKHAj33_VEeQdlG3VodS7DCgsfzRocotU0/edit#gid=0)

**Comment by Satendra-SR** [comment]
**Update from UNICEF:** The issue has been fixed now. 

**Action item for us:** Scheduling the call to 1098 for monitoring, once verified, we can roll out for all the users

**Comment by vivek-kumar-pandey** [comment]
Closing this issue as it is fixed now.
