### ISSUE TITLE
[Pilot] Test new program delivery for existing user

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#235]
**Is your feature request related to a problem? Please describe.**
We need to start a new program for the users who have completed one program.

With the current system, we have tested the program delivery for a single program per user, which we need to extend to multiple programs (a single active program at a time). To implement the capability, we need to figure out the following:
- [x] How our existing system is behaving if we start a new program for an existing user.
- [x] The registration table has a program associated with which gets updated as per the new request. Check how it behaves with the new program.
- [x] How User creation logic is behaving?
- [x] How User program logic is behaving? are we are able to create a new user program or update the existing program?
- [x] How other table logic is working as needed.

**Describe the solution you'd like**
- [x] List down all the possible changes we will require before getting started and giving the following program to the existing users.
- [x] Create new issues based on findings

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Satendra-SR** [comment]
@prtkdost Could you please share a test RP (a copy of flow that you are planning to use for new program delivery) that I can use for testing?

**Comment by Satendra-SR** [comment]
There are a few areas that need some tweaks to make the existing flow work for new programs for Alunimi users:

**1. User program selection**
- **Issue:** Currently, the user_program details are getting overridden in case the user is going through the registration flow again.
- **Proposed fix:** We need to check if the user has an active program, then override it, else, create a new user program for the user.

**2. User Registration**
- **Issue:** Currently, the program id is being overridden in the registration table each time, the user is going through the registration flow. We need to keep the first program id in the registration table.
- **Proposed fix:** If the user registration is completed, stop updating the program id.

**Comment by GauravGusain98** [comment]
This is done. The further action items will be targetted separately. Closing this now
