### ISSUE TITLE
[Sprint 1 - 2022] Documentation 

### ISSUE THREAD

**Issue by GauravGusain98** [DostEducation/RP_IVR_analytics#236]
**Requirement**
- [ ] Unification of all_call_record

**Describe the solution you'd like**
We will be using notion for documentation.

**Comment by Satendra-SR** [comment]
@prtkdost here is the document link for `all_call_records` which includes the approach and architecture we used.

**Comment by Satendra-SR** [comment]
This is done. Closing now.
