### ISSUE TITLE
Create user when we receive the callback from Kookoo

### ISSUE THREAD

**Issue by GauravGusain98** [DostEducation/RP_IVR_analytics#237]
**Is your feature request related to a problem? Please describe.**
Currently, the user is created when we get a webhook from Rapid Pro. While the registration is created as soon as we get call log events from Kookoo. 

So in case, a user didn't pick up the call then the registration will be created for the phone number but the user is still not created. 
So we want to create users at the same time we are creating registration.

**Describe the solution you'd like**
- [x] Create a new user on getting a first-time missedcall webhook call from KooKoo. 
- [x] Create user_program (with default program) on first missedcall itself. Check if the RP webhook will update the user program selection. Else, update the logic.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by vivek-kumar-pandey** [comment]
This issue was fixed and working. closing this issue
