### ISSUE TITLE
[Data archival] Data cleanup for Webhook logs

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#247]
**Is your request related to a problem? Please describe.**
We have two tables that we are using to capture webhook logs we are getting from RapidPro and Kookoo. It's been a while now and the table has grown up quite large.

1. Size of RP webhook logs table
```sql
SELECT pg_size_pretty(pg_total_relation_size('webhook_transaction_log')) as webhook_transaction_log;
```
<img width="364" alt="image" src="https://user-images.githubusercontent.com/39792899/153681973-4984a564-cefe-4af5-996e-c924e036cdc9.png">

2. Size of KooKoo webhook logs table
```sql
SELECT pg_size_pretty(pg_total_relation_size('ivr_callback_transaction_log')) as KooKoo_webhook_log_size;
```
<img width="512" alt="image" src="https://user-images.githubusercontent.com/39792899/153681998-1e943b69-d2f6-4e17-87c0-59e8e7e8ab50.png">

**Describe the solution you'd like**
- [x] Remove Processed webhook logs previous to 3 months from now.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Satendra-SR** [comment]
We have removed the older webhook log data and freed up the space.

initially, it was 28 GB, which came down to 19 GB after removing the logs and claiming the space. The log table, which was 10 GB earlier, is now around  1.1 GB

<img width="249" alt="image" src="https://user-images.githubusercontent.com/39792899/153821243-e82e1da3-d363-4ed6-a754-049de74ae7b3.png">

**Comment by GauravGusain98** [comment]
This is completed. Hence closing
