### ISSUE TITLE
Add functionality to mark user as un-subscribe/complete/terminate

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#257]
**Is your feature request related to a problem? Please describe.**
- Currently, we don't have the capability to mark the user program as un-subscribed in the Database, due to which, if a user chooses to unsubscribe from a program, the user_program status remains in progress, which is not correct.
- There are users who have completed the program but the user program is not marked as completed. - [link](https://docs.google.com/spreadsheets/d/1gprtYR4XYIWIc0g7Iy4QoI9FMao_oXZOrjFUVQwmLiw/edit#gid=111877665)

**Describe the solution you'd like**
- [x] Create table schema and table in database to map custom fields with columns and values that need to be updated **Points 2**
- [x] Create Logic to make changes in database as per custom_field_mapping  #268 **Points 3**

**Points - 1 (targeted separately)**
- [x] Backfill the user data who all have unsubscribed from a program
- [ ] Backfill the user_program status to complete for whom, the status is not marked as completed.

**Describe alternatives you've considered**
None

**Additional context**
None

**Impact**
- **Database**: There are 368 users on May 27 who have unsubscribed from the program, but were not marked as unsubscribed - [link](https://docs.google.com/spreadsheets/d/1gprtYR4XYIWIc0g7Iy4QoI9FMao_oXZOrjFUVQwmLiw/edit#gid=0)
- **From RapidPro:** There are 376 users who have unsubscribed from the program. There is a difference of 6 users that was due to webhook failure. We need to backfill then as well. 

<img width="299" alt="image" src="https://user-images.githubusercontent.com/39792899/170562681-c1204c37-c6da-4e73-97e4-b9bf7311fa21.png">

**Priority**
- Low, as it is not a user-facing issue and can be fixed quickly by backfilling

**Comment by Satendra-SR** [comment]
Keep the solution configurable

**Comment by Satendra-SR** [comment]
Need to check how we are terminating the users

**Comment by Satendra-SR** [comment]
We can mark user_program correspond to a user as complete/un-subscribe by getting the response in the custom field.

- If we get `group` of the user `Dost-Unsub-Users` then we can mark the user_program as unsub.
- If we get custom field `dost_program_completion` as True in `fields` then we can mark the user_program as complete.

For mapping the custom groups and fields in user_program table we can create a mapping table named `contact_fields_mapping`.
we can make the table structure as follows:
- **id:** Primary key contains sequence id.
- **field_type:** From which field we are getting the response or data. 
- **field_name:** Field containing the value to mark user as complete/unsub.
- **mapped_table_name:** Table where the value is going to add.
- **mapped_table_column_name:** Mapped table column where we are marking user status.
- **mapped_table_column_value:** Value to be add in the mapped table column.
- **expected_field_data_type:** Contains the data type of the expected_field_value. Nullable when `group` as field_type.
- **expected_field_value:** Contains the response of the user in the custom field.

**Comment by Satendra-SR** [comment]
### Test cases

#### Case 1:
- [ ] **Action** - Run the `dry_flow` for updating the status in `user_program`, the `dry_flow` payload should contain the **contact_field** **"dost_program_completion"** as **"Completed"**.
- [ ] **Desired Output** - The status of the latest active user_program will be updated for the user in the user_program table as **complete.**

#### Case 2:
- [ ] **Action** - Run the `dry_flow` for updating the status in `user_program`, the `dry_flow` payload should contain the **user_group** **"Dost-Unsub-Users"**.
- [ ] **Desired Output**: The status of the latest active user_program will be updated for the user in the user_program table as **unsub.**

**Comment by Satendra-SR** [comment]
### Steps to release functionality in production:

**Step 1:** Migrate the contact_fields_mapping model in production. (Create table schema in database).

**Step 2:** Add required mappings to the contact_fields_mapping table.
```sql
INSERT INTO "public"."contact_fields_mapping" ("id", "field_type", "field_name", "mapped_table_name", "mapped_table_column_name", "mapped_table_column_value", "expected_field_data_type", "expected_field_value") VALUES
(1, 'custom', 'dost_program_completion', 'user_program', 'status', 'complete', 'varchar', 'Completed'),
(2, 'groups', 'Dost-Unsub-Users', 'user_program', 'status', 'unsub', '', '');
```

**Comment by Sachinbisht27** [comment]
Closing as completed
