### ISSUE TITLE
Inactive content being calculated for unified alert

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#258]
**Describe the bug**
There is 18 such content that is active but on the current date (8th Apr), these contents are not going out for the last 1 week. [Here is the list.
](https://docs.google.com/spreadsheets/d/1z12olEAfJ_Yb7UV8ZiB3AUvC3NbofA6wLIgCadHpAwg/edit#gid=0)

**Expected behavior**
- [ ] Mark the inactive content as inactive in the database
- [ ] Update the RapidPro flows
- [ ] Backfill the data as required after discussion with @prtkdost 

**Additional context**
Originally captured here https://github.com/DostEducation/analytics-datasources/issues/27#issuecomment-1092654292

**Comment by GauravGusain98** [comment]
This issue will be fixed along with the issue https://github.com/DostEducation/RP_IVR_analytics/issues/249. 
We just need to check the logic of the alert.

**Comment by Satendra-SR** [comment]
Moving to purge for now, as we have another issue open which is a super set of this

**Comment by Satendra-SR** [comment]
Closing this as marked as purged in 2022
