### ISSUE TITLE
Terminate/unsubscribe old users

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#261]
**Is your request related to a problem? Please describe.**
There are users who are either no longer active or terminated already on Rapidpro

**Describe the solution you'd like**
- [ ] terminate remaining user from RapidPro - @prtkdost 
- [ ] Manually terminate the users from the application database. 
- [ ] Manually mark the users unsubscribe from the application database.
- [ ] Make sure the data is updated to BigQuery

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Satendra-SR** [comment]
Here is the list of inactive users for whom we can terminate the program

Users who haven't picked any callback: **345** (**38** users for whom first missedcall was on/after 1 April 22, **307** who didn't pick any call back yet and got enrolled **before April 22**)

https://docs.google.com/spreadsheets/d/1VTXMORhWWsmfjiKuUVR-uD9OUHo2gBJzKpQkrFNgYS4/edit#gid=55864945

**Comment by GauravGusain98** [comment]
This is completed. Closing this
