### ISSUE TITLE
Logic to update user data as per custom field mapping

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#268]
**Is your feature request related to a problem? Please describe.**
Update user data as per custom field mapping.

**Describe the solution you'd like**
- [x] Create the logic by which the custom field values are updated in the database for users in the `dry-flow`.

**Describe alternatives you've considered**
NA

**Additional context**
None

**Comment by vivek-kumar-pandey** [comment]
We are no more using the dry flow to update custom fields. closing this issue
