### ISSUE TITLE
Generate error logs in GCP from application

### ISSUE THREAD

**Issue by GauravGusain98** [DostEducation/RP_IVR_analytics#279]
**Is your feature request related to a problem? Please describe.**
We have seen some cases where GCP show some errors as debug log and due to this we don't get slack alerts. Also the information that GCP provide is not sufficient for debug. So we need to generate a customize error and send it to GCP logs.

**Describe the solution you'd like**
Need to integrate GCP logs in application and generate logs whenever any error occurs. [Reference Link](https://cloud.google.com/functions/docs/monitoring/error-reporting#functions-errors-log-python)

**Describe alternatives you've considered**
NA

**Additional context**
This task is a part of this diagnosis: [Link](https://github.com/DostEducation/analytics-datasources/issues/126#issuecomment-1161802655)

**Acceptance Criteria**
- [ ] The alert details should be shown in GCP logs

**Documentation**
- [ ] Create documentation of how we have integrated the GCP logs in the system.

**Comment by Sachinbisht27** [comment]
Closing as completed
