### ISSUE TITLE
Transaction Log Deletion Infra Setup

### ISSUE THREAD

**Issue by GauravGusain98** [DostEducation/RP_IVR_analytics#288]
**Is your feature request related to a problem? Please describe.**
We need to create a microservice which will daily remove the old kookoo and RP logs that are stored in the database. So first we need to setup the infrastructure for maintaining and deploying the code 

**Describe the solution you'd like**
- [x] Create GitHub repo
- [x] Add GitHub Templates 
- [x] Create private cloud function
- [x] Create scheduler
- [x] Update the cloud scheduler + cloud function setup document in Notion

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Acceptance Criteria**
- [x] The scheduler should have right permission so that it can trigger the cloud function

**Documentation**
https://www.notion.so/dosteducation/Setup-cloud-function-in-GCP-93225055f15e40d19b1d8bd66dd64365

**Comment by Satendra-SR** [comment]
Created a new infrastructure and it is working fine now. Closing
