### ISSUE TITLE
[Content Version] - Implement DB schema changes and update the RP flows 

### ISSUE THREAD

**Issue by vivek-kumar-pandey** [DostEducation/RP_IVR_analytics#294]
**Is your feature request related to a problem? Please describe.**
- We need to change the database as per the proposed db schema
 
**Describe the solution you'd like**
- Implement the schema change and update the database model
- Update Rapid Pro flows as per the requirement

**Describe alternatives you've considered**
NA

**Additional context**
Here is the suggested DB Schema and data flow model: https://www.notion.so/dosteducation/DB-Schema-and-Data-flow-Model-6375de819cf64add88413b140a896250

**Acceptance Criteria**
Database Changes are done according to the schema

**Documentation**
Add whatever documentation will be required here.

**Comment by GauravGusain98** [comment]
This is done. Closing this now
