### ISSUE TITLE
TypeError: Not a boolean value: 'Other' for has_smartphone in registration table

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#299]
**Is your feature request related to a problem? Please describe.**

There is an error with the webhook when the user is responding "Other" to the "Has Smartphone" question.

**Error:** This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). The original exception was: (builtins.TypeError) Not a boolean value: 'Other'.

This is happening through the prompt response mapping functionality. The application is trying to store non-boolean data in a boolean field, which is causing the issue

**Describe the solution you'd like**
- If the mapped column is boolean and we are getting "Other", just keep it null (do not process non boolean value)

**Describe alternatives you've considered**
- None

**Additional context**
- There are other field as well which might be falling in the same case

**Impact**
- 13 webhook error in the last 7 days
<img width="935" alt="image" src="https://user-images.githubusercontent.com/39792899/198948052-527687d2-0b2c-45d6-8858-b82f438b0105.png">

**Acceptance Criteria**
- The system should handle "other" responses for these mappings

**Documentation**
- Create a document so that the product team can use it for seeding.

**Comment by GauravGusain98** [comment]
The fix has been deployed. Closing this now
