### ISSUE TITLE
[BUG] Null value in column "partner_id" violates not-null constraint 

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#303]
**Describe the bug**
- Null value in column "partner_id" violates the not-null constraint. 

```python
 Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/layers/google.python.pip/pip/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NotNullViolation: null value in column "partner_id" violates the not-null constraint 
```

**Expected behavior**
The partner id should be a value (int)

**Screenshots**
<img width="764" alt="image" src="https://user-images.githubusercontent.com/39792899/200258104-299c8e2e-e634-46c3-ae96-5fa84839739c.png">

**Impact**
- From morning - 7th Nov 2020 (within 5 hours), it had 503 error reports.

**Additional context**
-None

**Acceptance Criteria**
- The error should be resolved
- The valid data should be inserted

**Documentation**
- [Notion document link - Replacing an existing system phone](https://www.notion.so/dosteducation/Replace-existing-KooKoo-number-with-new-number-732fa43e5c1346fb84faec44397c89ac)

**Comment by Satendra-SR** [comment]
**Backfilling**
- users
- Registration - user_id, partner_id
- user_program

**Comment by GauravGusain98** [comment]
This is fixed. Closing this now
