### ISSUE TITLE
Add content version in IVR prompt response table

### ISSUE THREAD

**Issue by GauravGusain98** [DostEducation/RP_IVR_analytics#309]
**Is your feature request related to a problem? Please describe.**
In near future there might be a case where we can send different IVR prompt response for different language. So in that case we also need content_version_id in IVR prompt response table. 

**Describe the solution you'd like**
**Solution 1:**
NOTE: We only get content_id and language_id from webhook
- We can add `content_version_id` in the `ivr_prompt` and `ivr_prompt_response` table
- When creating ivr prompt response entry we can populate content_version_id from ivr prompt data
    **Pros**
        - This way the system load can be minimized as we don't have to calculate content_version at every step
        - We will only have one source of truth i.e ivr prompt table
        - Large flow building will be comparatively less complex than solution 2. As we can reuse nodes. (You will get more context after going through Solution 2)
    **Cons**
        - When we have to do some change in content version, we also need to take care of updating the ivr prompt accordingly
        - In case our flow structure is like this:
            1. First few nodes are in hindi language
            2. After user prompt selection the flow language gets updated to a different language then the call_log record will show content_version_id of hindi language but in ivr_prompt_response as the content_version_id is fetched from ivr prompt table so the   content_version_id will be of the different language.
            3. The all_call_records will get affected as it will only show the content version related to the first webhook 

**Solution 2:**
NOTE: We only get content_id and language_id from webhook
- We only add `content_version_id` in `ivr_prompt_response` table. 
- Whenever we receive webhook from Rapid Pro, we will calculate content_version and will create and update the call_log accordingly
    **Pros**
       - We don't have to maintain the content_version mapping in ivr_prompt table
       - As now we are updating content_version in call_log table for every wehbook, so in both ivr_prompt_response and call_log table the content_version_id will be same
     **Cons**
        - System load will increase as we will calculate content version for every webhook
        - Large flow building will be complex. As In case our flow structure is like this:
            1. First few flows are in hindi language 
            2. After user prompt selection the flow language gets updated to a different language. Now as we move forward we cannot merge flow of different language they should be separated as the payload will contain the language_id of that particular language. This can be possible in the first solution

We can set language_id in user custom field of the Rapid Pro and based on that we can avoid the point 2 in cons section 

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Acceptance Criteria**
- [x] The content version id should be mapped correctly in ivr prompt response table

**Documentation**
Add whatever documentation will be required here.

**Comment by GauravGusain98** [comment]
After a discussion with Rudresh, we decided to go with solution 2 as it looks more clean. We also need to use user_custom_fields for language_id and should use that in the logic to calculate the content_version_id.

**Comment by GauravGusain98** [comment]
### Testing Criteria
- [x] If language id is null in custom fields then content version corresponding to hindi language should be picked
- [x] If language id is present then content version corresponding to that language should be picked

**Comment by GauravGusain98** [comment]
Added the steps to set language id of the user in the flow editor here
https://www.notion.so/dosteducation/RapidPro-webhook-setup-guidelines-c40c1d2b3a3b445fb3864e3e984c3eb7

**Comment by Sachinbisht27** [comment]
Closing as completed
