### ISSUE TITLE
[BUG] Sync Database and Rapid Pro for program and Timeslot

### ISSUE THREAD

**Issue by vivek-kumar-pandey** [DostEducation/RP_IVR_analytics#319]
**Describe the bug**
We had found that many users are having different record for their program and timeslot in the database and rapid pro 

**Expected behavior**
The timeslot and programs in the database should be same as Rapid Pro 

**Additional context**
This issue was [found here](https://github.com/DostEducation/analytics-datasources/issues/203)

**Acceptance Criteria**
- [x] Diagnose the root cause for data not matching
- [x] Backfill the correct data

**Documentation**
Add whatever documentation will be required here.

**Comment by Satendra-SR** [comment]
**Diagnosis Report:** 

- Found a wrong webhook payload in the RapidPro flow **FINAL-DOST-Pilot-OnboardingCall1.2**.
- Selected program details are missing from the final webhook payload therefore the system is updating the user_program to the default user_program 2.

**Solution:** 
- We have updated the correct webhook payload in **FINAL-DOST-Pilot-OnboardingCall1.2**.

**Wrong payload**
```json
@(json(object(
  "contact", object(
    "uuid", contact.uuid, 
    "name", contact.name, 
    "urn", contact.urn,
    "groups", contact.groups,
    "fields", contact.fields
  ),
  "flow", object(
    "uuid", run.flow.uuid, 
    "name", run.flow.name
  ),
  "channel", contact.channel,
  "flow_category", "registration",
  "flow_run_details", object(
    "uuid", run.uuid,
    "created_on", run.created_on
  ),
  "content_id", "1",
  "parent", parent,
  "results", foreach_value(results, extract_object, "name", "value", "category")
)))
```
**Updated correct payload**
```json
@(json(object(
  "contact", object(
    "uuid", contact.uuid, 
    "name", contact.name, 
    "urn", contact.urn,
    "groups", contact.groups,
    "fields", contact.fields
  ),
  "flow", object(
    "uuid", run.flow.uuid, 
    "name", run.flow.name
  ),
  "channel", contact.channel,
  "flow_category", "registration",
  "flow_run_details", object(
    "uuid", run.uuid,
    "created_on", run.created_on
  ),
  "content_id", "1",
  "parent", parent,
  "program_details", results.intro_1_signup_1_selection_program_optin,
  "results", foreach_value(results, extract_object, "name", "value", "category")
)))
```

**Comment by vivek-kumar-pandey** [comment]
On diagnosing we found four issues:
| sl | Issue | Fix |
|---|----|----|
|1.| In Onboarding call, `FINAL-DOST-Pilot-OnboardingCall1.2`, program details were missing from the flow. Due to this the program selected by users was not updating in the database, instead the default program was getting updated in the DB | We fixed the flow and monitor it for few time, now the flow is working fine and users program are correctly filled |
|2.| On first day of onboarding call `FINAL-DOST-Pilot-OnboardingCall1.2`, if user does not selects a program and the next day if he gives a missed call then he gets two onboarding calls ie.  `FINAL-DOST-Pilot-OnboardingCall1.2` and `FINAL-DOST-Pilot-OnboardingCall2`.  In the OnboardingCall2 flow, we were setting the program as 2 in the very beginning. So now if the user again selects a program, then he will be enrolled to that, otherwise he will be moved to program 2 no matter what was his previously selected program. | Prateek fixed the flow and moved the program updation to P2M1D1 flow. Kriti updated the programs in the rapid pro for these users |
|3.| There was a mistake in the `FINAL-DOST-MissedCallFeature3` in which the users were getting moved to P1M10D1 after the P2M9D4 call. | We had fixed the flow now |
|4.| The users are getting multiple onboarding calls by making missed calls and in one of that they selects a program and in the another they don't select any program making it to update the DB for default program | This is an edge case so we will be monitoring it as tolerance for now|

**Comment by Sachinbisht27** [comment]
Closing as completed
