### ISSUE TITLE
Eliminate User module content from RP-IVR system

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#323]
**Is your request related to a problem? Please describe.**
- The table `user_module_content` is used to capture which module and content went out on which day. Recently, we added a new table called `program_sequence` which holds the seq of each module content. This table id is being mapped to the `call_log` table where we can get the sequence - https://github.com/DostEducation/RP_IVR_analytics/issues/224
- Now the new table is working fine, we can eliminate the table `user_module_content` as it is taking time and resources to process these details by the system for each webhook call.
- If we see the current database query insights, inserting data into this table is taking most of the time (which is worthless for us now)
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/39792899/207773402-55ff147e-b28b-4e68-aa5a-0854f872c793.png">

**Describe the solution you'd like**
- [x] Archive data from the `user_module_content` table (if not done with already running data archival)
- [x] Removed the table `user_module_content` from the database.
- [x] Remove all the code dependencies
- [x] Remove all the code dependencies from the migration service.
- [x] Remove all the dependencies from Bigquery.
- [x] Deploy changes on both the services (RP-IVR-analytics & data migration services) and give a test run to make sure everything is working fine.

**Describe alternatives you've considered**
- None

**Additional context**
- This table is not required anymore as we introduced the `program_sequence` table which is doing the same job - https://github.com/DostEducation/RP_IVR_analytics/issues/224

**Acceptance Criteria**
- [x] We should have a backup (archived data) for `user_module_content` table
- [x] The system should stop processing user module content for each webhook
- [x] The table should be removed from the database
- [x] The table should be removed from BIgQuery
- [x] The data migration service shouldn't process/migrate the `user_module_content`.

**Documentation**
- None

**Comment by vivek-kumar-pandey** [comment]
- [ ] User_module_content cleanup

**Comment by Sachinbisht27** [comment]
Closing this issue as completed now.
