### ISSUE TITLE
[BUG] User_program is updating to default when the user is not selecting any program.

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#325]
**Describe the bug**
The existing users are getting multiple onboarding calls by making missed calls and in one of them, they select a program, and in the other, if they don't select any program and disconnect the call. Then the system is updating the user_program to the default program in the database.

**To Reproduce**
1. Misscall on the system_phone to get an Onboarding call.
2. Disconnect without selecting the user_program.
4. See the user_program in the database "Updated to user_program 2" which is default user_program.

**Expected behavior**
If the existing user disconnects the call without selecting the user_program then the user_program should not be updated to default.
If the new user disconnects the call without selecting the user_program then the user_program should be updated to default.

**Screenshots**
![image](https://user-images.githubusercontent.com/39792899/209630626-88c9b8a1-1ffc-4bf3-8d7e-f7ab0b392ed6.png)

**Acceptance Criteria**

- [x] Diagnose the bug and fix it.
- [ ] Backfill the data for affected users.

**Documentation**
Add whatever documentation will be required here.

**Comment by Satendra-SR** [comment]
**Test cases:** 
- In registration flow update `user_program` with `selected_program_id` only.
- In registration flow if user not selected `program_id` then update existing `program_id` for the user in `user_program`.

**Comment by Sachinbisht27** [comment]
Closing as completed
