### ISSUE TITLE
Calls failing with status Invalid Number

### ISSUE THREAD

**Issue by GauravGusain98** [DostEducation/RP_IVR_analytics#355]
**Describe the bug**
 We are getting failed status as `InvalidNumber` from KooKoo for many calls. Due to this users making missed calls are not getting callbacks. This status is also seen for many daily scheduled calls. 

We need to see why we are getting this status for these calls. 

**Impact**
For February 2023 this status has been seen for **34304** calls. Here is the [list](https://docs.google.com/spreadsheets/d/1KOWdzXB4b4hKqyDfq-gCHdBWve2JJb4EpfrOc9RgEU4/edit#gid=532381351) of these calls

**Expected behavior**
These numbers should have got the calls as these are valid user numbers

**Priority**
High - User experience is getting impacted

**Comment by vivek-kumar-pandey** [comment]
This issue not replicating anymore. So closing this issue
