### ISSUE TITLE
[BUG] Scheduled regular calls not delivered properly in the RP_IVR 

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#356]
**Describe the bug**
In the RP_IVR system scheduled regular calls were not delivered properly on `27-02-2023`.
The calls are not scheduled for some active users in their selected timeslot. 
- Calls are delayed more than the usual delay time. Some users get their call out of the preferred time slot.
- Some enrolled users didn't get their regular calls on `27-02-2023`.

**Diagnosis**
- List of the users who got affected by this issue in the system. [[Link](https://docs.google.com/spreadsheets/d/1QFARFXaeiIHKIn5lTPR_plWMXQXy2EOj-n_RYQKUm5o/edit?usp=sharing)]
- Possible reason for this delay:
     - In the afternoon timeslot, the system phone `8037835217` started making a lot of inbound or outbound calls to itself, which possibly caused an increase in queue size and it took some time to complete these calls and stayed in the queues for a long time.
     - There could be some misconfigurations at KooKoo/RapidPro end, which caused making inbound/outbound calls to itself by the `8037835217` number.
- In the diagnosis, we found that most of the affected users are from the afternoon timeslot.

**To Reproduce**
This is the first time we are facing such an issue. And the issue occurred at the KooKoo/RapidPro end. 

**Expected behavior**
Diagnosis of the issue and why it occurred and resolve the issue.

**Screenshots**
Inbound/Outbound calls to itself by the 8037835217 number.
  
![Screenshot 2023-02-28 191439](https://user-images.githubusercontent.com/39792899/221872156-5cd3a7c5-252e-4805-86ea-8da8228d19dc.jpg)

**Acceptance Criteria**
- Calls should deliver properly for active users in their preferred time slot.

**Documentation**
Add whatever documentation will be required here.

**Comment by Satendra-SR** [comment]
On `02-Mar-2023`, the same issue reoccurred and caused the JH system phone with the number `8037835217` to generate an excessive number of inbound and outbound calls to itself, as indicated in the picture below:

**Inbound and Outbound calls made in `02-Mar-2023`** 
![image](https://user-images.githubusercontent.com/39792899/223027297-b8bb6dff-b50d-42ba-98b1-f295ba5f2ba6.png)

This issue caused the queries of new users to fail once again. The root cause of this problem is the presence of the system phone number `8037835217` in the RapidPro system, which schedules calls to itself.

The first ten entries of the call_log_event data (shown below) reveal that RapidPro received a missed call from the `8037835217` number first, leading to the creation of the user at the RapidPro level.
<img width="1111" alt="image (8)" src="https://user-images.githubusercontent.com/39792899/223028412-055add09-7d22-419e-96be-7d1cedf88c1d.png">

**Comment by vivek-kumar-pandey** [comment]
This issue was fixed after discussion with the unicef/Rapid Pro team. There was some backfilling also required which was done. Closing this ticket now
