### ISSUE TITLE
[BUG] User not found in the database.

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#366]
**Describe the bug**

**The user is not found in the database:** 
We found that Some users are receiving regular calls from RapidPro, but their "user" is not created in the user table till now. 
These users are registered in the registration table with a status of pending or incomplete, and their user_id value is null.
When these users respond to any prompts, the system is unable to retrieve their user details based on their phone number, which generates an error log.
There are some new users as well who are not present in our database but getting calls from RapidPro.

**To Reproduce**
- We can see the error logs in the [Monitoring Dashboard: Production.](https://console.cloud.google.com/monitoring/dashboards/builder/bec02bf8-99c0-4d39-8df4-06f7a66f2dab;duration=PT1H;tzId=Asia%2FCalcutta?project=cryptic-gate-211900)

**Expected behavior**
All users getting calls from RapidPro should be present in our database.

**Impacted users:**
- 18-03-2023 - [ 2616 users. ]
- 21-03-2023 - [ 2546 users. ]
- The count is varying because when the newly affected users are responding to their program and time selection prompt then a user was created for those.

**Screenshots**
![image](https://user-images.githubusercontent.com/39792899/226258293-ae17e89e-33c4-4993-9ad5-825b9b89d91d.png)

**Additional context**

**Acceptance Criteria**
- [ ] Figure out how new users are getting impacted and do whatever changes are required.
- [ ] No error log should generate anymore.

**Documentation**
Add whatever documentation will be required here.

**Comment by Satendra-SR** [comment]
### For the new users:
- Sometimes the system is not receiving any webhook from RapidPro. That's why some users are not having their entries in the user table.
- The user creation logic works only when the system receives a registration flow category webhook in RP_IVR analytics.
- But some users got their registration created because the RP_IVR callback has the functionality to create registration when any user miss calls to the system.

**Action Items:**

- [ ] We need to Implement #237.
- [ ] Test the functionality is working correctly.

**Acceptance Criteria:**
- [ ] New users should create on getting a first-time missed-call webhook call from KooKoo.
- [ ] Create user_program (with default program) on the first missed call itself. Check if the RP webhook will update the user program selection. Else, update the logic.


### For the old users:
- For all the old users who are receiving their calls from RapidPro and not in our system. We need to create their user entry and update their other required details.

**Action Items:**
- [ ] Backfill all the user and registration details.

**Acceptance Criteria:**
- [ ] Old users should have their user details in the user's table.
- [ ] Should have their user_program data, registration data, user_group data, and user_custom_fields data in their respective tables.

**Comment by vivek-kumar-pandey** [comment]
This issue is fixed now. Closing it
