### ISSUE TITLE
[Churned Users] - Add cron to create churned call records

### ISSUE THREAD

**Issue by GauravGusain98** [DostEducation/RP_IVR_analytics#369]
**Is your feature request related to a problem? Please describe.**
For churned users we want to generate call records and mark them as `failed_churned`. So we need to create a scheduler file that will daily create call records for churned users. 

**Describe the solution you'd like**
- [x] Create a scheduler  that will daily and  update the logic to create call records for churned users. 
- [x] The call should be scheduled according to selfpacedlogic
- [x] The call_status should be `failed_churned`

**Comment by vivek-kumar-pandey** [comment]
The cron is created and working fine. Closing this ticket
