### ISSUE TITLE
Reduce the KooKoo call statuses as per our use case.

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#38]
The Kookoo provides different call statuses. See the list of different call status here under `Call Back Url Parameters` heading.

**Comment by Satendra-SR** [comment]
Checkout this [link](https://networking.ringofsaturn.com/Routers/isdncausecodes.php) detailed cause (status description).

**Comment by Satendra-SR** [comment]
Checkout[ this document ](https://docs.google.com/document/d/1Czwavkx7-efvyul891H_SV7WjBZPARJV6etzXj9--Ug/edit?usp=sharing)for reference

**Comment by gandhisonia** [comment]
Need to know what NoAnswer/StatusRinging and InterWorkingUnspecified are for.

**Comment by Satendra-SR** [comment]
@gandhisonia posting the details here you have share. 

> sonia  12:15 PM
Re: Call statuses @Satendra @Rudresh Shrotriya
> 1. We would need the status for the following major cases:
> 2. User picking up the phone (delivered and picked up)
> 3. User engaged on another call (delivered but user busy on a different call)
> 4. User rejecting the call (delivered but user cut the call)
> 5. User not picking up (delivered but no answer)
> 6. Call not going through/User not receiving the call owing to system issue (not delivered)
>
> We currently have the following status in our Exotel system --> `busy`, `completed`, `failed`, `in-progress`, `no-answer` --- let me know if we can continue with some/all of these. (edited)

**Comment by rudresh** [comment]
@gandhisonia sharing [document](https://docs.google.com/spreadsheets/d/1XnUtuiKm5Ss-Nr8bCak3pJng10-jU1hljUX196UD7-s/edit#gid=0) having the kookoo call statuses mapped to the ones you shared above.  Please have a look.

**Comment by Satendra-SR** [comment]
Closing this items as the mapping is already shared
