### ISSUE TITLE
[BUG] - Error while handling webhooks for dry_flow.

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#381]
**Describe the bug**
On 31st May we started receiving so many error logs on RP IVR production.  

```
 (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back  
```

**Add diagnosis details**
- A total of 19,904 error logs were received on 31 May.
- The timing from error logs, when started generating or ends, is the same as the timing when `DataSync-Dryflow` runs. 
- So, the impact was on mid-night dry flow only, things started working fine after that.
- The Cloud function to see the number of requests we got in this time interval (though we have the queuing system in place) and it also seems fine.

**To Reproduce**
1. Go to Monitoring Dashboard.
2. Check RP IVR prod error logs for 31 May.
3. See errors.

**Screenshots**
Error logs:
![image](https://github.com/DostEducation/RP_IVR_analytics/assets/39792899/33c5a95c-ff35-4fd5-af33-a031c9e93613)

Generation timing:
![image](https://github.com/DostEducation/RP_IVR_analytics/assets/39792899/a5416a4a-e12f-457c-bc9e-bcb3ead7bd1f)

**Additional context**
N/A

**Impact**
Add the issue impact here.

**Action items**
Add the action items required here.

**Documentation**
Add whatever documentation will be required here.

**Comment by vivek-kumar-pandey** [comment]
This issue was diagnosed and everything is working fine now. Closing this issue
