### ISSUE TITLE
Adding logger in the rp-ivr-webhook-handler to generate logs in cloud function.

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#401]
**Is your feature request related to a problem? Please describe.**
Currently, we don't generate different levels of logs in the cloud function. We need to generate different levels of logs from the system.

**Describe the solution you'd like**
- [x] Figure out how we can generate different levels of logs from the system.

**Describe alternatives you've considered**
NA

**Additional context**
- [x] We should be able to generate info, and error logs from the system

**Documentation**
Add whatever documentation will be required here.

**Comment by Sachinbisht27** [comment]
This is deployed on the production, and working fine so closing this item.
