### ISSUE TITLE
Research how we can run the migration for this application

### ISSUE THREAD

**Issue by vivek-kumar-pandey** [DostEducation/RP_IVR_analytics#410]
**Is your feature request related to a problem? Please describe.**
We currently manage database schema changes manually in our RP_IVR system, which can be error-prone and lacks version control. We need to implement a database migration system to handle schema changes more efficiently and reliably.

**Describe the solution you'd like**
We propose implementing a database migration system using a suitable migration tool to automate the process of applying and managing schema changes. For that we need to do some research on how we can implement it in RP_IVR and which tool would be better.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Acceptance Criteria**
- [ ] Come up with documenting the findings and share with dost team

**Documentation**
Add whatever documentation will be required here.

**Comment by Satendra-SR** [comment]
This is a duplicate issue of https://github.com/DostEducation/RP_IVR_analytics/issues/411
