### ISSUE TITLE
Integrate and stabilize the database migration 

### ISSUE THREAD

**Issue by vivek-kumar-pandey** [DostEducation/RP_IVR_analytics#412]
**Is your feature request related to a problem? Please describe.**
We need to integrate the database migration system that we are coming up with in the solutioning of the research  and ensure its stability.

**Describe the solution you'd like**
We need to implement the database migration tool and ensure the stability of the migration process to prevent data loss or inconsistencies.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Acceptance Criteria**
- [ ] The data migration tool is working fine and all the existing table are included in the migration

**Documentation**
Add whatever documentation will be required here.

**Comment by Satendra-SR** [comment]
Already capture in https://github.com/DostEducation/RP_IVR_analytics/issues/416
