### ISSUE TITLE
Automate database migration in RP-IVR project

### ISSUE THREAD

**Issue by Sachinbisht27** [DostEducation/RP_IVR_analytics#413]
**Description**
- Initially, our plan was to develop the user interface (UI) for the RP IVR application using Django and utilize Django migrations for any database structure updates. However, we later decided to pause the development of the RP IVR UI, resulting in the absence of any database migrations specifically designed for the RP IVR component.

**Problem Statement**
- When someone installs the application, they encounter difficulties in creating the necessary database tables because there is no migration file available for the RP IVR. To address this issue, it is essential to generate migration files that are specifically tailored for creating the required database tables during the initial setup of the application. These migration files will enable a smooth installation process and ensure the proper functioning of the RP IVR component within the application.

**Impact**
- As the RP IVR application is open source, missing migration files displays the poor engineering process of the team and the organization.
- Ease out the onboarding experience. As it will be very difficult for anyone to understand the system without database schema.

**Possible Solution**
- [x] Use Flask migrations to create migration files for the existing database structure

**Breakdowns**
1. Research how we can run the migration for this application: 2 pointer
2. Research on database migration library/plugin in Flask: 1 pointer
3. Integrate and stabilize the database migration - 3 pointers
4. Create/write database migration files: 2-3 pointers
5. Test the migration files on different environments: 1-2 pointer
6. Document the migration process: 1 pointer
**Ballpark Estimates**
- Two - 1 pointer
- Two - 3 pointer
- Two - 2 pointer

**Comment by Satendra-SR** [comment]
#410 
#412 
#413
#414

**Comment by Sachinbisht27** [comment]
Deployed on production so closing it now.
