### ISSUE TITLE
Install Packages and Create database migration files

### ISSUE THREAD

**Issue by vivek-kumar-pandey** [DostEducation/RP_IVR_analytics#414]
**Is your feature request related to a problem? Please describe.**
Once we are ready with the packages that we can use for the database migration, we can install the packages and create the migration file for the existing database

**Describe the solution you'd like**
- [x] Install the database migration package
- [x] Create the migration files for the existing db

**Describe alternatives you've considered**

**Additional context**

**Acceptance Criteria**
- [x] Packages are working fine 
- [x] The migration files are created for the existing db

**Documentation**
Add whatever documentation will be required here.

**Comment by Sachinbisht27** [comment]
[Sheet](https://docs.google.com/spreadsheets/d/1tw8ONfLk1Jgw-QvUVv5G9-fRO-ryOsoUFbNS7FAJ-wg/edit?usp=sharing) of the changes in the table schema of RP_IVR application
