### ISSUE TITLE
[FEATURE] Integrate and stabilize the database migration in the RP_IVR service.

### ISSUE THREAD

**Issue by Sachinbisht27** [DostEducation/RP_IVR_analytics#416]
**Is your feature request related to a problem? Please describe.**
We have implemented the new database migration functionality in the RP_IVR service. Now we need to integrate the functionality into the CD because every time we add a new table structure migration version in the system it will upgrade the database schema in the different environments automatically. 

**Describe the solution you'd like**
- [x] Check for the best implementation for the automatic upgrade of migration versions in different environments.
- [x] Integrate and test to stabilize functionality.
- [x] Check how we can manage our data of staging and production when we are going to run the migrations for the first time.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Acceptance Criteria**
- [ ] The data should not be affected and the new migration versions will run smoothly in the staging and production environment.

**Documentation**
Add whatever documentation will be required here.

**Comment by Satendra-SR** [comment]
This is completed, we are going with the Github action for the database migrations
