### ISSUE TITLE
[FEATURE] Test and deploy the new migration files on different environments.

### ISSUE THREAD

**Issue by Sachinbisht27** [DostEducation/RP_IVR_analytics#417]
**Is your feature request related to a problem? Please describe.**
We have implemented the new database migration functionality in the RP_IVR service. After the research and testing in one of the servers. Now we are ready to deploy the changes in the different servers.

**Describe the solution you'd like**
- [x] Deploy it on staging and test whether all the RP_IVR functionalities are working fine or not.
- [x] Deploy the changes on the production and monitor the changes.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Acceptance Criteria**
- [x] The changes should work fine and the webhooks data should be saved normally on every table.

**Documentation**
Add whatever documentation will be required here.

**Comment by Satendra-SR** [comment]
The changes have been deployed and tested on the staging server and tested fine.

**Comment by Sachinbisht27** [comment]
Deployed on production so, closing it now.
