### ISSUE TITLE
Setup queries for System Health Metrics

### ISSUE THREAD

**Issue by rudresh** [DostEducation/RP_IVR_analytics#45]
- [x] Create data sources for the required tables.
- [x] Is data flow seamless between Kookoo/RP Webhooks and the new database?
- [x] Are Users getting added to the system after receiving missed calls?Is there a lag?
- [x] Is the District and State of user getting captured? Is it getting captured correctly?
- [x] Are experiences getting created for the Users? Are programs getting assigned correctly? First program as well as the subsequent ones?
- [x] Is data captured through IVR responses getting updated to the User's data in the tables?
- [x] Are calls being scheduled at the time given as preference?
- [x] Is there any issue with call scheduling? Is the statusof the call getting updated correctly?
- [x] Is the self-paced program running smoothly - call scheduling wise?
- [x] Is the duration of the call getting captured correctly?
- [x] Make a chart to check call lag in picking up the call
- [x] Are prompts getting delivered on time/at the right place?
- [x] Are responses getting recorded correctly?
- [x] Lag between the user picking up call and the user getting content
- [x] Lag for missed call
- [x] Have Users been added to the database? (Users signed up by partner last 7 days)
- [x] Are new users being mapped to the correct partner, exophone and program?
- [x] Have calls gone out? (Calls by status and day)
- [x] Any major changes in call connectivity? (%age calls by status and day)
- [x] Are any time slots overpopulated?
- [x] Has campaign info been updated for all scheduled calls? (Campaign records with missing info)
- [x] Are there any active users for whom calls are not being scheduled?
- [x] Do any users have more than 1 active experience?
- [x] Are users who opted-in to streaks being started correctly?
- [x] Are attempts being scheduled properly?
- [x] Are calls being scheduled for all active programs?
- [x] Are incoming missed calls being responded to?
- [x] Are responses to IVR prompts being processed correctly?
- [x] Are users who finish programs not being marked as completed?

**Comment by Satendra-SR** [comment]
The first round of data sources is ready now for use. Closing this item.
