### ISSUE TITLE
RP-IVR analytics - python and flask upgradation activity in application and infrastructure

### ISSUE THREAD

**Issue by Sachinbisht27** [DostEducation/RP_IVR_analytics#455]
We are currently using `Flask 1.1.2`, which is getting older, and the latest version `Flask 3.0.0` was upgraded on `Sep 30, 2023`. Within these releases, there are lots of minor and major releases which include breaking changes and it is recommended to upgrade the application dependencies timely to avoid any security vulnerability with the older versions.

With this, we are currently utilizing `Python 3.8` for which, the support is going to end by Oct 2024. On the Cloud function, we do have support up to `Python 3.12`, which is aligned with what we can target in this ticket.

![Image](https://github.com/DostEducation/RP_IVR_analytics/assets/39792899/bb82ebfa-5df6-4eba-992a-d0b9c12a4cc6)

Whenever we will be targeting to upgrade the application and infrastructure, we have to deal with upgrading other packages and make them compatible with `Python 3.12` and `Flask 3.0.0`.

- [x] Upgrade the flask version from `Flask 1.2.2` to `Flask 3.0.0` - 5 pointers in total (around a week)
    - Here is the list of changes mentioned in official documentation -[ Flask version upgrade change logs](https://flask.palletsprojects.com/en/3.0.x/changes/#version-1-1-2)
    - The upgrades should be done sequentially, by upgrading one version each time to update the codebase based on the changes mentioned in the change log and test the functionality - **3 pointers**
    - Test the entire application functionality - **2-pointer**
    - Bug fixes and enhancement required during upgrade (While testing before production release) - **2 pointers**
- [x] Upgrade the Python from `Python 3.8` to `Python 3.12`. Flask 3.0.0 is compatible with Python 3.8 and above, so we can pick it up once the Flask upgrade is done. - **2 pointer**
- [x] Upgrade the staging cloud function to `Python 3.12` and run the final testing on staging - **1 pointer**
- [ ] Prepare the release for production, including the Rollback plan in case anything goes wrong, we can swiftly move it to the old state - **1 pointer**
- [x] Release on Production and Monitor for a few days - **1 pointer**

**Comment by Sachinbisht27** [comment]
Closing as completed now and released on production

**Comment by Satendra-SR** [comment]
- https://github.com/DostEducation/RP_IVR_analytics/issues/457
- https://github.com/DostEducation/RP_IVR_analytics/issues/458
- https://github.com/DostEducation/RP_IVR_analytics/issues/456
- https://github.com/DostEducation/RP_IVR_analytics/issues/461
