### ISSUE TITLE
[FEATURE] Upgrade Flask version sequentially to 3.0.0

### ISSUE THREAD

**Issue by Sachinbisht27** [DostEducation/RP_IVR_analytics#456]
**Is your feature request related to a problem? Please describe.**
We are currently using Flask 1.1.2, which is getting older, and the latest version Flask 3.0.0 was upgraded on Sep 30, 2023. Within these releases, there are many minor and major releases, including breaking changes. It is recommended to upgrade the application dependencies timely to avoid any security vulnerability with the older versions.

**Describe the solution you'd like**
- [x] Upgrade the Flask version from Flask 1.2.2 to Flask 3.0.0

**Describe alternatives you've considered**
NA

**Additional context**
Here is the list of changes mentioned in official documentation -[ Flask version upgrade change logs](https://flask.palletsprojects.com/en/3.0.x/changes/#version-1-1-2)

**Acceptance Criteria**
- [ ] The upgraded package versions and dependencies should work fine.

**Documentation**
Add whatever documentation will be required here.

**Comment by Satendra-SR** [comment]
This is released. Closing the issue now
