### ISSUE TITLE
[FEATURE] Upgrade Python Version to Version 3.12

### ISSUE THREAD

**Issue by Sachinbisht27** [DostEducation/RP_IVR_analytics#458]
**Is your feature request related to a problem? Please describe.**
We are upgrading our application with the latest versions of the packages and dependencies. To do the same we need to upgrade the Python package from Python 3.8 to Python 3.12. Flask 3.0.0 is compatible with Python 3.8 and above, so we can pick it up once the Flask upgrade is done.

**Describe the solution you'd like**
- [x] Upgrade the Python package from Python 3.8 to Python 3.12

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Acceptance Criteria**
-  [x] The upgraded package versions and dependencies should work fine.

**Documentation**
Add whatever documentation will be required here.

**Comment by vivek-kumar-pandey** [comment]
There are some packages which are not compatible with the python 3.12 version.
- For example, the request package is used by google-auth. Even on using the latest version for both packages, we are getting following error:
![image](https://github.com/DostEducation/RP_IVR_analytics/assets/49094385/391b9f77-9953-4051-bd49-cdfa999f3bbd)

This error suggest that the `requests` is not compatible for the `google auth`. However on a different python version, it is working correctly. Looking further we found that `Requests` latest version is even only compatible till python version 3.11:
![image](https://github.com/DostEducation/RP_IVR_analytics/assets/49094385/21e9cae7-6157-4fc0-83a4-c5c93dc70643)

So we are upgrading the pyhton version to 3.11

**Comment by Sachinbisht27** [comment]
Closing as completed now and released on production
