### ISSUE TITLE
Analysis of current infrastructure and cost 

### ISSUE THREAD

**Issue by vivek-kumar-pandey** [DostEducation/RP_IVR_analytics#473]
**Is your feature request related to a problem? Please describe.**
Dost product team is planning to expand the user base in UP districts, so they wanted to know about the load that can be currently handled by the system, after which we will need to upgrade the system. Also, they wanted to know the cost increase in Postgres and BigQuery.

**Describe the solution you'd like**
- [x] Share the Cost Analysis of current system 
- [x] Share the load that can be handled by the current system

**Describe alternatives you've considered**
- Perform load testing on the current system, but it will take time, and a team is needed with the data on an urgent basis. So we shared the analysis based on the load testing we did previously about 1.5 years ago.

**Additional context**
Here is the[ slack thread](https://dosteducation.slack.com/archives/CFZSGGRAP/p1705894200988259) for the discussion

**Acceptance Criteria**
- [x] Share all the details of the current system and cost
- [x] Share a draft to be mailed to the UNICEF team

**Documentation**
Add whatever documentation will be required here.

**Comment by Satendra-SR** [comment]
Here is the link to the analysis - https://www.notion.so/dosteducation/Technical-Overview-Document-dec6318dddce482297c8d45ec6fe6731

**Comment by Satendra-SR** [comment]
### Detailed breakdown:

1. In our initial conversation, we estimated it for 1-2 pointers (attached the screenshot below from Slack conversation).
2. At starting, we decided to start with one pointer and then update as needed.
3. Share the Cost Analysis of current system - The initial work was to analyse the cost estimates for each component, which took around 2 hours of work. [The details are added in this document](https://www.notion.so/dosteducation/Technical-Overview-Document-dec6318dddce482297c8d45ec6fe6731#755b4055b6c44e5c9d6aa9ea28fc54cb)
4. Shared the load that can be handled by the current RP-IVR system - We analyse the current load on the system and went through the last analysis of application capacity and shared a tentative data. This took additional 1.5 hours. [The trails are here in the Slack thread](https://dosteducation.slack.com/archives/CFZSGGRAP/p1705995778934789?thread_ts=1705894200.988259&cid=CFZSGGRAP).
5. We had to communicate with Unicef team regarding capacity planing at RapidPro and Kookoo. Drafted the email conversation and shared with Kriti. [The trails can be found here in slack](https://dosteducation.slack.com/archives/CFZSGGRAP/p1706007732772519?thread_ts=1705894200.988259&cid=CFZSGGRAP). This took additional 0.5 hours to draft the details and shared.



<img width="665" alt="image" src="https://github.com/DostEducation/RP_IVR_analytics/assets/39792899/217c8cd4-9cfa-40ea-a418-cfaee7bfef6b">
