### ISSUE TITLE
[FEATURE] List down the details of the current load (RapidPro and KooKoo)

### ISSUE THREAD

**Issue by Sachinbisht27** [DostEducation/RP_IVR_analytics#475]
**Is your feature request related to a problem? Please describe.**
We want to do load testing in our application. We want to list down all the details required to analyze the current load in the application.

**Describe the solution you'd like**
- [x] List down current request handling of the RP_IVR architecture.
- [x] Analyze how many webhook requests can be handled by the system.
- [x] Create a report and share it with the team.

**Describe alternatives you've considered**
NA

**Additional context**
Main issue: #471 

**Acceptance Criteria**
The report should be able to highlight the analysis of the current load in the application.

**Documentation**
Add whatever documentation will be required here.

**Comment by Sachinbisht27** [comment]
**Link to the documentation:** https://www.notion.so/dosteducation/Load-Testing-in-RP-IVR-a89a4bc874a341399cb2bdecf4794fc9?pvs=4

**Comment by Satendra-SR** [comment]
This is completed - marking it closed
