### ISSUE TITLE
Migration plan for UNICEF pilot data

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#60]
- Come up with the migration plan for UNICEF pilot data

**Comment by rudresh** [comment]
Refer [this sheet ](https://docs.google.com/spreadsheets/u/1/d/1NbMgn_XlSlM3CeBhOwa79Ss5LLlqfPI6/edit#gid=442519185)for planning the migration

**Comment by rudresh** [comment]
We need to fill the data in the following tables:
1. registration
2. user
3. user_program
4. user_module_content
5. ivr_prompt_response
6. call_log
7. call_log_event

Tables we can populate with the shared sheet
- [ ] registration
- [ ] user
- [ ] user_program
- [ ] populate the `user_id` and `registration_id` for the missing rows in the `user_custom_fields` table. 
- [ ] populate the `user_id` and `registration_id` for the missing rows in the `user_groups` table.

**Comment by Satendra-SR** [comment]
Sharing the mapping sheet below that we will be using for migration
https://docs.google.com/spreadsheets/d/1Zqz7fjeemzwDq4BeAKVxTKLyTvgpmHj22FVj055kgDs/edit#gid=0

**Comment by Satendra-SR** [comment]
- [ ] Create sub-story for migrating `user_module_content`

**Comment by Satendra-SR** [comment]
- [ ] Create sub-story for migrating `user_module_content`

**Comment by Satendra-SR** [comment]
Closing this item as we have migrated the required data for now.
