### ISSUE TITLE
Make 1 chart each (health + funnel) for getting started

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#67]
**Is your feature request related to a problem? Please describe.**
For getting started, we need to create two analytics chart on DataStudio and pass it to the Dost team for the reference.

**Describe the solution you'd like**
- [x] Need to create 1 chart for System health metric
- [x] Need to create 1 chart for  funnel metric
- [x] Share relevant documentation (if any)
- [x] Create required data sources that will help generating the metrics. 

**Describe alternatives you've considered**
No alternative for now. These charts are required to get started.

**Additional context**
None

**Comment by Satendra-SR** [comment]
As this is an in progress item, moving it to in-progress bucket

**Comment by rudresh** [comment]
The details of all the data sources can be found [here](https://docs.google.com/document/d/1JqcgkVityDzIgepayKoZyusf81w0C74LwtsRZQkpTYU/edit). This document contains all the data sources name as well as the queries used to create them.

Apart from the document, each data sources has the relevant documentation added to them.

**Comment by Satendra-SR** [comment]
The datasources and the sample charts are completed and passed to analytics team. Closing this out.
CC @gandhisonia @prtkdost
