### ISSUE TITLE
Webhooks change for prompts used in filling other tables/columns

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#69]
**Is your feature request related to a problem? Please describe.**
The system is capturing ivr prompt response in `ivr_prompt_response` table. But for populating other table column, we need to make changes for each data set. We need to comeup with a plan to do it efficiently.

**Describe the solution you'd like**
We can divide the item into two sub items:
- [x] Research and come up with a plan to make it efficient and how we can reduce this cycle.
- [x] Execution, need to make those changes in the system

**Dev Notes:**
We can consider making changes in prompt naming conventions so that we can easily extract the info from prompt itself.

**Describe alternatives you've considered**
Check if we can pass additional info from Rapid Pro itself.

**Additional context**
None

**Comment by Satendra-SR** [comment]
There are multiple ways we can handle this, sharing the possible ways below:

1. Add table + column name to prompts itself. I this case, the system at backend will check if table name exists in the prompt name, make the changes
    - **Advantages**:
        - It should be easy to implement.
        - Minimal code changes required when adding a new prompt.
    - **Shortcomings**:
        - Need to re look into naming conventions we discussed earlier. It can take longer as there is an existing nomenclature and it can impact others as well.
2. Define mapping at codebase: In this case, we will add a mapping at codebase and whenever 
    - **Advantages**:
        - It should be easy to implement.
    - **Shortcomings**:
        - Changes will be required at codebase when adding a new prompt.
3. Define mapping at database level
    1. If 1-1 mapping exists (1 prompt will be responsible for populating a single table's column), add new columns to the same table.
    2. If 1-n mapping exists(1 prompt response will be responsible to populate multiple table/columns), add a new table for mapping prompts and other tables mapping.
    - **Advantages**:
        - No code changes will be required at code base when adding a new prompt
    - **Shortcomings**:
        - The pre-seeding data will be required each time when adding a new prompt (We are anyway adding these data while adding prompt details)

All the  three options are doable and will works fine. I would recommend to go with third options as it will be have a clean implementation, we don't have to make changes for adding a new prompt and we will have data available (in database) if in case we need.

**Comment by prtkdost** [comment]
I also feel 3rd option is good.

**Comment by Satendra-SR** [comment]
We are going with the third option. Based on our use case, one-one mapping is what we need right now. This means, one prompt will be responsible for populating any single column of a particular table.

**Comment by Satendra-SR** [comment]
We can use phone number as identifier.

**Comment by Satendra-SR** [comment]
### Test steps:

- [ ]  Test all four condition:
    - [ ] Morning
    - [ ] Afternoon
    - [ ] Evening
    - [ ] Other/Default
- [ ] Overriden
- [ ] Test whether multiple columns in multiple tables are getting filled.

**Comment by Satendra-SR** [comment]
Need to test the multiple system phone, it is failing for now

**Comment by Satendra-SR** [comment]
Need to update based on registration id. Create a new issue.

**Comment by Satendra-SR** [comment]
Testing this item on staging, moving to accepted.

**Comment by Satendra-SR** [comment]
@prtkdost Deployed in on production. I've seeded the mapping table for the preferred time slot as well. Closing this item.
