### ISSUE TITLE
Evaluate Metabase and ELK (Graphana) as a BI tool option

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#7]
- [x] Evaluate Metabase and ELK (Graphana) and Data Studio as a BI tool option

**Comment by rudresh** [comment]
Keeping my finding in this [document](https://docs.google.com/document/d/1IOBmpwnegW1LJTuZGIgfvQuMb99BwSR0w3tjy82Ombc/edit)

**Comment by rudresh** [comment]
Given the different option and features, we can go ahead with [Grafana](https://docs.google.com/document/d/1IOBmpwnegW1LJTuZGIgfvQuMb99BwSR0w3tjy82Ombc/edit) as the BI tool for us.

**Comment by Satendra-SR** [comment]
Update: Considering non tech user, the team is exploring Data studio.

**Comment by Satendra-SR** [comment]
Went with Data studio, closing this item.
