### ISSUE TITLE
Webhook & schema changes to monitor user group switching

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#70]
**Is your feature request related to a problem? Please describe.**
We are handling user groups switching at Rapidpro level. Whenever a flow runs for a user, it remove the user from that particular group and add it to a different group. There are a few chances where the user is not getting removed from a group/ getting added to other group, and user is either keep receiving the same call or multiple calls due to multiple group assignment.

We need to capture the use's group assignment.

**Describe the solution you'd like**
Capture the user's group assignment whenever a flow runs.
- [x] Come up with the plan and db schema changes
- [x] Implement the changes based on discussions.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Satendra-SR** [comment]
### The proposed solution would be:

1. Each time, a flow will run, we will pass the use's group info to webhook
2. At system level:
    1. Check if user-group association is already captured in Database.
    2. If not exists:
        1. Capture user-group association.
        2. Check the active association each time when handling webhook requests. If the association is still active, mark if **ACTIVE**. Else, mark if **IN-ACTIVE**.
        3. Check for the previous associations, it those are still active, keep them as **ACTIVE**. Else mark it **IN-ACTIVE**.

### Required Database changes:

There are two possible ways to capture these data with required change in the DB

### Solution 1:
Having a single table called **user_groups**

Table structure:

| column      | type | options | foreign key |
| ----------- | ----------- |----------- |----------- |
| id      | int       |              |              |
| user_id   | int        |             |      user -> id        |
| registration_id      | int       |              |     registration -> id         |
| group_name   | varchar   |             |        |
| status| varchar       |     active / in-active         |              |
| created_on   | timestamp        |             |              |
| updated_on   | timestamp        |             |              |

-----------------------------


###  Solution 2:
Having two tables **user_groups** and **group** (or **contact_groups**). In this approach, we will need to pre-populate the groups table data.

Table structure:

1. **user_groups**

| column      | type | options | foreign key |
| ----------- | ----------- |----------- |----------- |
| id      | int       |              |              |
| user_id   | int        |             |      user -> id        |
| registration_id      | int       |              |     registration -> id         |
| group_id   | int        |             |     groups -> id         |
| status| varchar       |     active / in-active         |              |
| created_on   | timestamp        |             |              |
| updated_on   | timestamp        |             |              |

2. **groups** or **contact_groups**

| column      | type | options | 
| ----------- | ----------- |----------- |
| id      | int       |              |
| name   | int        |             |
| status| varchar       |     active / in-active         |
| created_on   | timestamp        |             |
| updated_on   | timestamp        |             |

**Comment by prtkdost** [comment]
This looks good. I think first option is better but we can discuss before finalizing.

**Comment by Satendra-SR** [comment]
We can fo with option 1

**Comment by Satendra-SR** [comment]
This got close but Github automation, reopening for testing.

**Comment by Satendra-SR** [comment]
This is deployed on UAT and ready for testing.

**Note:** Please use these two flows for testing or create new for testing.
1. [DOST-Test-P2M7D4-devteam](https://rapidpro.ilhasoft.in/flow/editor/dfd14f24-ebba-41c8-b5d6-cea1adcf36a2/)
2. [FINAL-DOST-test-OnboardingCall-devteam](https://rapidpro.ilhasoft.in/flow/editor/07f364fa-fdd2-492f-a4e6-704c280f07a7/)

### Steps to test:
1. Schedule a call from above flows.
2. Check `user_group` table for latest entry for your phone number.
3. Check the table is populated with correct user group information.

**Comment by Satendra-SR** [comment]
This is working fine on staging and production as well.

**Comment by rudresh** [comment]
Everything is working as expected on prod. Closing this out
