### ISSUE TITLE
Add documentation to the data sources and the columns

### ISSUE THREAD

**Issue by rudresh** [DostEducation/RP_IVR_analytics#78]
**Is your feature request related to a problem? Please describe.**
We are creating data sources in Data Studio. For any new person to understand the purpose of the data source and the columns we need to add some descriptions to them.

**Describe the solution you'd like**
We will use the description columns in the respective data source to give a brief about the columns. The `id` column will have the general description for the data source itself.

**Describe alternatives you've considered**
None

**Additional context**
This helps us manage the data sources and give proper documentation for any newcomer.

**Comment by Satendra-SR** [comment]
Confirm and close if completed

**Comment by Satendra-SR** [comment]
Confirmed, closing now.
