### ISSUE TITLE
Enhancements related to lags

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#82]
For a workaround, we need to make following changes.

- [x] Content id in call log table
    - [x] Code changes to capture content id in call logs table.
    -  [x] Check if we can backfill these data
- [x] Capture RP flow name in call log table.
- [x] Populate the RP Created On for the older records.
- [x] Create a new data source for call_lag with following details: 
Phone number, flow_run_uuid, call_sid, pick_time, created_on, rp_created_on, date, difference between rp_created_on and pick_time, is case 2 lag, content_id, content_duration, call_listen_seconds, diff between listen_second and content duration, is case 4 lag. 
The case details can be found in the comments below.

**Comment by rudresh** [comment]
Excerpts from chat conversation with Prateek
> There are 4 types of lag
> 1. Where Kookoo does not record pickup time. There is a delay for Kookoo fails to understand the call is picked up and thus send the info to RP. In this case, the Kookoo pickup time is incorrect for example called in actually pickedup at 12:00:10 but Kookoo records show pickup time as 12:00:40. So after 12:00:40 only the call is made to RP for nextsteps hence the delay. There is no way to identify such issues other than someone actually reporting that they picked up much earlier than actually shown.
> 2. The delay after the pickup and kookoo sending call to RP for next steps.
> 3. The delay in RP sending the API call for audio. This is mostly under 1 second and rarely goes to 2-3 seconds. We can measure the combined delay of point 2 and 3 by time diff in our records.
> 4. After RP send the API call back for playing the audio, Kookoo is taking a lot of time in actually playing it.
> For point 1 they have changed the network provider today. The cases of 2-3 are around 9% today, it was 16% yesterday and 65% on Wednesday last week. For the 1 and 4 cases, we do not have data so will relying on self reported instances to find such issues. There are not much proposed solutions right now. Even diagnosing is difficult.
>

**Comment by Satendra-SR** [comment]
This is deployed on UAT and ready for testing.

**Note:** Please use these two flows for testing or create new for testing.
1. [DOST-Test-P2M7D4-devteam](https://rapidpro.ilhasoft.in/flow/editor/dfd14f24-ebba-41c8-b5d6-cea1adcf36a2/)
2. [FINAL-DOST-test-OnboardingCall-devteam](https://rapidpro.ilhasoft.in/flow/editor/07f364fa-fdd2-492f-a4e6-704c280f07a7/)

### Steps to test:
1. Schedule a call from above flows.
2. Check `call_log` table for latest entry for your phone number.
3. Check if `content_id` and `flow_name` column is populated with right information.

**Comment by Satendra-SR** [comment]
We are able to capture content id and flow name now. Closing this.
