### ISSUE TITLE
[Research] Alerts for Webhook Failure

### ISSUE THREAD

**Issue by prtkdost** [DostEducation/RP_IVR_analytics#87]
**Is your feature request related to a problem? Please describe.**
We want to identify cases where webhooks are failing due to any technical error or manual error.

**Describe the solution you'd like**
For technical error - check google logs for failure of webhooks and setup email+slack alerts for the same. Whenever alerts come open an issue and fix it.

For manual error - Decide on missing data to check through which we can identify incorrect webhooks, and then create alert/chart for the same to be monitored with other system health metrics

**Describe alternatives you've considered**
NA

**Additional context**

Need to comeup with a plan based on the research.

**Comment by Satendra-SR** [comment]
Added alerts in GCP for cloud functions errors. Now we will be receiving alerts in the Slack channel.

**Comment by Satendra-SR** [comment]
Getting notifications on slack successfully. Closing now.
