### ISSUE TITLE
Fix logic of picked_up_call records

### ISSUE THREAD

**Issue by prtkdost** [DostEducation/RP_IVR_analytics#88]
**Describe the bug**
Logic of pickedup_call_records and call_lags table. Records in call_log_events for which no webhook entries are found in call_logs should come in pickedup call records with null RP entries.

**Comment by Satendra-SR** [comment]
### Points to be considered:

1. There is no relationship between `call_log` and `call_log_event`.
2. There are some entries in `call_log_event` with picked call which doesn't have anything related in `call_log` table.
3. Need to change the logic in datasource where we are joining these two tables (On joining, the` call_log` columns should come as null corresponding to above `call_log_event`)

**Comment by rudresh** [comment]
Based upon the discussion remove the 2 min check from the query as we are now picking only those record where the time difference is closest to zero.

**Comment by rudresh** [comment]
@prtkdost I've updated both `pickedup_call_records` and the `call_lags` data sources.  Please test it.

**Comment by Satendra-SR** [comment]
This is good to go @prtkdost @rudresh based on the conversation on the weekly call.
@rudresh please take the required action

**Comment by Satendra-SR** [comment]
This is complete, closing this now.
