### ISSUE TITLE
Fix unicef_user_experience table - not getting populated correctly

### ISSUE THREAD

**Issue by prtkdost** [DostEducation/RP_IVR_analytics#89]
**Describe the bug**
User_experience table is not getting created properly. There are 170 users getting calls daily but entries created only for 30-40 of them.

**To Reproduce**
Compare outbound call records with experience table
Compare rapidpro reports with experience table
Check Actual webhook calls received in codebase specifically content id (and thus content name) with the number of records created in experience table.

**Expected behavior**
Count in experience table should be equal to all the users who are picking up a content call on any given day.

**Screenshots**

**Additional context**

**Comment by Satendra-SR** [comment]
### Points to be consider:

#### For 5th may:
1. Total picked calls went out for unique system users = 114
2. Total entries in `user_module_content` = 28

Ideally this figure should match.

### Tech Notes:

1. Check RP if the payload is passed correctly.
2. Check the webhook logic for adding entries in `user_module_content`

**Comment by Satendra-SR** [comment]
Confirm on backfilling the data.

**Comment by Satendra-SR** [comment]
Deploy and test ASAP

**Comment by Satendra-SR** [comment]
Issue have been fixed, closing now.
