### ISSUE TITLE
Make data source - All_call_records

### ISSUE THREAD

**Issue by prtkdost** [DostEducation/RP_IVR_analytics#90]
**Is your feature request related to a problem? Please describe.**
Unable to exclude callbacks (other specific calls based on RP) from call log events when doing joins in data studio.

**Describe the solution you'd like**
Thus make a new data source similar to picked_up_call records, where all call records are there, and all RP info is filled for the calls we have RP info and for others it's null (for all call statuses not just answered).

**Describe alternatives you've considered**
No but we can explore other options to solve this problem

**Additional context**
check chart 6 row 10 of system ops metrics in [Dost_metrics](https://docs.google.com/spreadsheets/d/1oaC6QHrdA901UiDw8qAlbC2PzZ7GkM4_L1N8_QsIcXM/edit?usp=sharing) sheet for example.

**Comment by Satendra-SR** [comment]
@prtkdost please check and confirm. If it looks good, please close  the item.

**Comment by rudresh** [comment]
@prtkdost I've update the data source with the updated logic. Please verify.

**Comment by Satendra-SR** [comment]
Working fine and accepted by @prtkdost. Closing now.
