### ISSUE TITLE
Improve call lag calculation

### ISSUE THREAD

**Issue by Satendra-SR** [DostEducation/RP_IVR_analytics#95]
**Is your feature request related to a problem? Please describe.**
The call duration has inconsistency between the call logs coming from callback and api.

1. Check if the KooKoo api is true source for call duration and call lag
2. If there are gaps, ask KooKoo to resolve the gap.
3. If applicable, change call lag calculation based on KooKoo.

**Describe the solution you'd like**
- Plan to parse KooKoo API logs and store them in our database.
- Plan to create the required data source.
- Plan to store call logs

**Describe alternatives you've considered**

**Additional context**
Once the research is done, create issues as required

**Comment by rudresh** [comment]
Shared the findings with Prateek for this. Prateek to follow up with the KooKoo team.

**Comment by rudresh** [comment]
Update `pickedup_call_records` to include 
1. `true_pick_time` (coming from the kookoo log api parsing)
2. `type 1 lag` - from true pick time to kookoo sending the request, in seconds
3. `type 2 lag` - from kookoo sending the request to RP and getting back the audio response, in seconds
4. `type 3 lag` - total lag - type 1 lag - type 2 lag, in seconds
5. `total lag` - difference between total_call_duration(in kookoo api log) and call_duration (in kookoo callback), in seconds. If total_call_duration is missing then total_call_duration = `call_duration`
6. `true_call_duration` = `total_call_duration`
7. `listen_seconds_capped` = min of (call_duration, content_duration)
8. `prompt_duration` = `call_duration` - `listen_seconds_corrected`

Decide the frequency for the log parsing. Every hour or 30 mins?
Create monitoring alert for log parsing and kookoo callback.

**Comment by Satendra-SR** [comment]
### Action items:

- [ ] Propose the high-level architecture to host the script that will capture, parse, and store the logs in the database.
- [ ] Create scripts for Polling and Parsing logs.
- [ ] Staging and Production deployment of the application based on the finalized architecture.
- [ ] Update the data sources based on the [above comment](https://github.com/DostEducation/RP_IVR_analytics/issues/95#issuecomment-841166741)

**Comment by Satendra-SR** [comment]
Created Five stories based on the action items from this story. Closing this out.
