### ISSUE TITLE
User_registration and IVR_prompt_response table not getting updated properly

### ISSUE THREAD

**Issue by prtkdost** [DostEducation/RP_IVR_analytics#97]
**Describe the bug**
a User has selected a program but the program_id field in the registration table is showing null. This user has also made a prompt selection on Apr 29 but the one captured in the IVR table is for May 2 only. Same is the situation with several other users.
![image](https://user-images.githubusercontent.com/69189579/117405346-1f627c00-af29-11eb-9a40-6954489cc7b0.png)

**To Reproduce**
For registration table - see entries with status completed but program_id null.
For IVR prompt table - download results from onboarding_call flow and compare the results with our IVR prompt table

**Expected behaviour**
All prompts answered should be populated in ivr_prompt_response table.
In registration table the status should be 'completed' as soon as program is selected and program id and signup date should be updated.

**Screenshots**
![image](https://user-images.githubusercontent.com/69189579/117405497-5f296380-af29-11eb-9ac3-9d4a5511f563.png)

**Additional context**

**Comment by Satendra-SR** [comment]
The wrong press is not getting captured, Check for 21st May.
Also, check flows `TTR_...`

**Comment by Satendra-SR** [comment]
Confirm on backfilling the data.

**Comment by Satendra-SR** [comment]
Confirm on `This user has also made a prompt selection on Apr 29 but the one captured in the IVR table is for May 2 only`.

**Comment by Satendra-SR** [comment]
-[ ]  backfill signup dates as well in registration table.

**Comment by Satendra-SR** [comment]
Backfilled the data, and the changes are working fine now, closing.
